### ISSUE TITLE
Do you accept donate?

### ISSUE THREAD

**Issue by netroby** [skywind3000/kcp#1]
Do you accept donate?

this is amazing protocol. like it very much

Do you accept donate?

**Comment by skywind3000** [comment]
thanks and happy new year ! Happy to see it useful to others. In my project we have also added a FEC mechanism to improve packet loss cancellation: packet to send: p1,p2,p3,p4; packet actually sent: p1, p2, p3, p4, p5(p5=p1 xor p2 xor p3 xor p4), if any of these five packets lost, it can be recovered by xor all other four packets together. We use these method with KCP to stream audio and video packets and get a better result.

**Comment by skywind3000** [comment]
thanks and happy new year ! Happy to see it useful to others. In my project we have also added a FEC mechanism to improve packet loss cancellation: packet to send: p1,p2,p3,p4; packet actually sent: p1, p2, p3, p4, p5(p5=p1 xor p2 xor p3 xor p4), if any of these five packets lost, it can be recovered by xor all other four packets together. We use these method with KCP to stream audio and video packets in realtime and get a better result.

**Comment by netroby** [comment]
Nice working, please continue to improve the protocol, if the document can be more detail would be very appreciate
