### ISSUE TITLE
Is IKCP is good for live file streaming

### ISSUE THREAD

**Issue by peererror** [skywind3000/kcp#103]
I am currently developing  an  app for file streaming like video file to 1 or many clients .I have done this using udp but due to packet lost I am facing many issues .So I was looking into your library it is looking good will it work for my needs ?. I want to know before I give it a try

**Comment by skywind3000** [comment]
kcp has already been used successfully in video / audio streaming:

https://github.com/skywind3000/kcp/wiki/Success-Stories

You can try kcptun as a beginning
