### ISSUE TITLE
使用最少带宽应该怎么配置？仅保证可靠传输就行。

### ISSUE THREAD

**Issue by ohsorry** [skywind3000/kcp#104]
如题，下层是udp，也不打算向前纠错，如何配置kcp能用最少的带宽？最少也要比tcp多出10%？

**Comment by caoli5288** [comment]
README里面有。
> 普通模式： ikcp_nodelay(kcp, 0, 40, 0, 0);

普通模式下带宽消耗应该跟tcp相差无几。（考虑到kcp协议的一些特征可能是略多一点点点点）

**Comment by ohsorry** [comment]
好的，我试试

**Comment by ohsorry** [comment]
`struct IKCPSEG`这个是报文头吧，kcp出手很大方啊，都是u32， 考虑压缩下吗？@skywind3000

**Comment by skywind3000** [comment]
IKCPSEG 有很多是内部状态使用，不会被发出去的，整个包头只有24字节，tcp也有20个字节，你拼死，能省多少个字节？和tcp一样少4个字节？没什么用，因为你 UDP + IP 包头就有8+24=32字节，你自己给udp加点头，少说也要加上8字节。

全部一加：8+24+8+24=64字节，光靠kcp这里节省4个字节，变成60个字节，意义不大。

**Comment by skywind3000** [comment]
微软的 xbox live 的udp数据传输，算上加密全部有90个字节的 overhead

**Comment by ohsorry** [comment]
包头24个字节？那还可以接受。格式是什么样的？

**Comment by skywind3000** [comment]
格式是啥意思？什么格式？

**Comment by ohsorry** [comment]
没什么我想看看你的报文头怎么设计的
