### ISSUE TITLE
我在使用的时候,用着用着segment空了

### ISSUE THREAD

**Issue by a11s** [skywind3000/kcp#110]
ikcp.c 1032行
Exception thrown: read access violation.
segment was nullptr.

为了加快响应,每次send以后flush
send rcvsize 都是65535
nodelay interval 1
rto 5
nc 1

每次发送一个包给对面,收到对面结果以后,再发下一个包,再等响应..如此循环
大约1分钟最后会收到这个错误.很容易复现
现在没什么方向,是我忽略了什么重要的步骤吗?
谢谢

**Comment by skywind3000** [comment]
你是不是多线程访问同一个 kcp对象？

**Comment by a11s** [comment]
认真看了一下,确实不是一个线程.修改以后跑了10几分钟没有再次复现出来.

**Comment by skywind3000** [comment]
但凡你读下文档，或者看一下issue列表都不会发生的事情。
