### ISSUE TITLE
ikcp_recv有时会同时接收到几个包，是否属于正常现象？

### ISSUE THREAD

**Issue by dbskccc** [skywind3000/kcp#111]
ikcp_nodelay(kcp_obj, 1, 20, 2, 1);
按照标准流程，ikcp_input后调用ikcp_recv，有时网络延时大，会同时收到发送方面发送的好几个包，2-3个，在同一个ikcp_recv中，请问这是正常现象吗？

**Comment by skywind3000** [comment]
正常，你看 test.cpp，每次要进入一个 while 循环，持续调用 ikcp_recv 收包，直到没有包了。

**Comment by dbskccc** [comment]
哦，那就行，我调试看kcp-go每次接收都只有一个包，感觉这个实现比较方便使用，如果一次调用ikcp_recv只会收到一个包，那用户的代码逻辑可以简单些，否则还要在ikcp_recv的代码里增加判断有几个包的代码，包里的数据还得包含各个 包的长度数据

**Comment by skywind3000** [comment]
你就是用裸的 udp 或者 tcp，每次接收也是需要一个 while 循环，持续接收到 EAGAIN 才终止的啊，这是个标准规则，有啥好疑惑的呢？又有啥好修改的呢？

**Comment by dbskccc** [comment]
我错了，应该是kcp-go默认打开了stream mode导致的

**Comment by sea520-coder** [comment]
裸的udp不粘包，不需要while循环
