### ISSUE TITLE
编解码问题

### ISSUE THREAD

**Issue by DarkIdiot** [skywind3000/kcp#114]
看了ikcp.c文件的编解码，实在不理解大端编解码代码为什么是那样完成的，求作者解释下。谢谢。

**Comment by ichenq** [comment]
ikcp_encode16u和ikcp_encode32u是按little endian的方式压入协议header的

`
/* encode 32 bits unsigned int (lsb) */
static inline char *ikcp_encode32u(char *p, IUINT32 l)
{
#if IWORDS_BIG_ENDIAN
	*(unsigned char*)(p + 0) = (unsigned char)((l >>  0) & 0xff);
	*(unsigned char*)(p + 1) = (unsigned char)((l >>  8) & 0xff);
	*(unsigned char*)(p + 2) = (unsigned char)((l >> 16) & 0xff);
	*(unsigned char*)(p + 3) = (unsigned char)((l >> 24) & 0xff);
#else
	*(IUINT32*)p = l;
#endif
	p += 4;
	return p;
}
`

**Comment by DarkIdiot** [comment]
谢谢啦。
