### ISSUE TITLE
关于UNA的疑问

### ISSUE THREAD

**Issue by BreezingLad** [skywind3000/kcp#124]
在KCP的发送函数中（flush）,首先会发送需要确认的包。从协议来看，有UNA机制，此处是处于何种考虑没有采用呢？
即是说，针对每一个收到的报文，都会发送一个确认报文回去。
我的想法是这样的：
此处可以先计算acklist中连续的最小ACK号，在发送数据或者回送ACK时，就直接把该ACK捎带上。这样就不需要给对端回送ACK。而在发送函数的最后，检测如果没有发送任何数据或者ACK报文，再单独回送一个ACK做连续确认。

**Comment by skywind3000** [comment]
请搜索 “选择性重传”

**Comment by BreezingLad** [comment]
我问的这个是确认机制，不是重传机制吧。
比如发送放收到1、2、3、4、5、8、10这几个报文（与是否重传无关），现在KCP处理逻辑是针对每个报文组装一个ACK报文（共7个ACK报文）。但是可以只需要回送2个ACK报文（8、10）其中，8、10号报文中的ACK字段填5，表示5以前的报文都已经接收到了。
这样在网络没有那么烂的情况下，应该会少发送很多ACK报文。

**Comment by jimzhong** [comment]
TCP有这个机制，叫做延迟ACK，目的是节约带宽。KCP的应用场景和TCP不全相同，因此并不需要这么做。

**Comment by skywind3000** [comment]
他自己连程序都没有读懂就来开issue了，连una和ack是啥都没搞清楚
