### ISSUE TITLE
亲,VS2013下，提示重定义，，，

### ISSUE THREAD

**Issue by zhaokaixs** [skywind3000/kcp#13]
请问如何配置windows下的环境配置~

**Comment by skywind3000** [comment]
提示重定义什么东西？

**Comment by zhaokaixs** [comment]
搞定了,,,我是在windows下编译使用,   你给的test.cpp
#include <stdio.h>
#include <stdlib.h>

#include "test.h"
#include "ikcp.c"  //把这个注释掉就好了,,


还有个问题是,,没太看懂具体怎么用，， 是不是要把自己的网络库接口传给kcp的回调里，让kcp调用网络库接口来发包呀。。。
