### ISSUE TITLE
kcp is delay on local lan 

### ISSUE THREAD

**Issue by peererror** [skywind3000/kcp#131]
Hi,
I am creating image streaming application using kcp. When I run this on local lan kcp have high delay and it is also taking very high bandwidth like 10mb/s . I am using following parameters to init kcp. 
  
  ```
ikcp_nodelay(kcp, 1, 10, 1, 1);
  ikcp_setmtu(kcp,1640);
  ikcp_wndsize(kcp, 128, 128);
```

**Comment by skywind3000** [comment]
参数没设置对，请看看 wiki

**Comment by peererror** [comment]
fix the issue by increasing socket receive buffer .last  thing I want to ask is there a way to to call update in 5ms . 
thanks for the help and great work !!!
