### ISSUE TITLE
程序卡在ikcp_flush

### ISSUE THREAD

**Issue by 0ZeroCN** [skywind3000/kcp#136]
for（p=kcp->snd_buf.next; p!=&kcp->snd_buf; p=p->next）
{
...
}

p指向下一个节点为它本身，导致无限循环，卡在for里面

还有传输速率也不快

**Comment by skywind3000** [comment]
这循环你没看明白么？怎么可能会卡。你自己哪里用错了破坏了内部结构了吧。

**Comment by 0ZeroCN** [comment]
谢谢回复，刚开始用的好好的，过一段时间会就出现这种情况，链表是被破坏了，但就是不知道是什么原因。

**Comment by skywind3000** [comment]
你不同线程里操作了同一个kcp对象没？

**Comment by 0ZeroCN** [comment]
用的单线程，参考了asio-kcp

**Comment by skywind3000** [comment]
那显然是你哪里非法内存访问了啊

**Comment by jacob-job** [comment]
> 你不同线程里操作了同一个kcp对象没？

我在多个线程里操作同一个kcp对象，有加锁，在void ikcp_flush(ikcpcb *kcp)的1030行IKCPSEG *segment = iqueue_entry(p, IKCPSEG, node);是空指针，导致后面段错误了。请问多线程使用需要注意什么？

**Comment by caoli5288** [comment]
需要注意：不要多线程访问

**Comment by DyncEric** [comment]
我也遇到卡死的情况，就在ikcp_flush里面

**Comment by skywind3000** [comment]
KCP 代码没那么脆弱，问题九成九是你们自己代码没写对，请先检查自己的代码，如果觉得是 KCP 的问题，请提供最小重现方式，和调用栈信息，这种不明不白的来个卡住了，我也帮不了你。

**Comment by DyncEric** [comment]
> KCP 代码没那么脆弱，问题九成九是你们自己代码没写对，请先检查自己的代码，如果觉得是 KCP 的问题，请提供最小重现方式，和调用栈信息，这种不明不白的来个卡住了，我也帮不了你。

多线程访问的问题，已经改了在跑压测了，多谢
