### ISSUE TITLE
代码有些地方让人误解啊

### ISSUE THREAD

**Issue by ugksoft** [skywind3000/kcp#139]
a.没demo,纯C的demo(纯C因为函数式,条理上比c++清晰度上稍好一点), 最简单的收发 这个很关键!!! 一边发送个hello A,另一个回复个helloB之类的,,还有多久回复helloB才算收到了的,大量数据比如直播时
  大概的应用情况,要说一下,而不是让别人翻代码去理解

b.output之类的,写成 Send之类的一肯就明白的名字,写成output,初看代码时,不知道是recv后输出的,还是网卡输出到,没demo,只能啃完代码才理解.

c.大多数人,只希望马上用起来,看看是否适合自己应用,有demo的看demo,没demo的,代码足够简单,一眼就清楚调用逻辑,用熟了后,才会去看代码(为了掌控全局,大多数会去看的)
 所以你应该写清楚这些, udp包头 Raw数据情况,之类的,图片形式给出,,一些数据块需要一起的包,比如关键侦200KB,但一个消息包,比如文字消息,或是控制消息,是独立的,多个包之间没有绝对的顺序关系,
打洞比较麻烦费时,用户尽量在一个洞上通讯时,kcp如何解决?
大多数开发者,累点自己写代码,而不是调用别人的,或是去阅读别人的代码
 
d. 其它一些给用户建议的
1.用kcp肯定是想效率的,那么,mtu分包是548还是14xx推荐值文档,国内大概情况之类

2.内外网穿透相关内容,挂上连接,告诉用户,穿透由用户完成,穿完后,调用kcp之类的, 说上一句两句,就能给刚刚看你代码的很大帮助了

3.有时用户可能喜欢原有自己的udp保障算法,丢包算法, 比如语音时,2个包+一个xor包方式,避免丢包
但是视频时,不允许浪费10-20%的带宽,5%都不允许,直接丢包,  你的说明中,写的是"10-20%"太吓人了
(比如双人视频,20%可以,多人会议时,720p,1080p视频)

**因代码没有100%看完,所以,有理解错的,当我没说,见谅**

**Comment by skywind3000** [comment]
2) input/output 对应底层协议收发，send/recv 对应上层用户 api 接口，这个 wiki 里早就说过了，还有插图： https://github.com/skywind3000/kcp/wiki/Network-Layer 把 output 改成send才是更混淆视听。
3) 没法画出一个KCP->UDP->IP的通用协议包头栈，因为你自己实现连接层，必然还会加不少字节的包头，你可以理解成 KCP->你自己的协议头->UDP。
4) KCP是纯算法实现，换句话说，用户负责底层链接收发，必然就已经实现了链接握手包括加密等，否则怎么负责底层链接收发呢？KCP无需再多做一遍。

**Comment by tidus5** [comment]
@ugksoft    照着网上的udp代码，加上kcp 写了个demo。 可以参考下https://github.com/tidus5/kcp_demo
不大懂 c/cpp， 有些api 不大会用，仅供参考

**Comment by ugksoft** [comment]
谢谢了, 最早是没注意到作者在wiki写了东西, 因为大多数wiki里没内容,就没想到去wiki看一下

只是,作者对性能带宽写的有点...
10-20%的浪费,太吓人,语音还好,但视频通讯之类,要是浪费10-20%带宽,太恐怖了

,数据包等没写清楚RAW包结构,在代码中,我草看了一下,也没有找到一个固定的struct结构
所以才会有这个贴子

这些是开发者,刚拿到一个东西后,需要第一眼知道的东西,大家不想花了n多时间后,才发现不适合自己
浪费时间

不过,现在也不想这个了,贴子也可以洁了,  我udp通讯数据,需要节省带宽,高度控制部分,自己处理了,费点代码,总比看别人代码,去匹配自己的应用要好一些

后面,会考虑使用kcp的,

作者可能很忙,没时间, 其它有谁写了代码了,特别是移动等复杂网络应用的,希望能给出一个分析报告
比如网络现实情况比如
  NAT出去后,会不会几分种移动NAT的后出口IP就换了,
  每秒udp发包速度限制, (移动下载100Mbps,上传50Mbps,但是让不让你长时间跑满就难说了)
  每秒不同端口的,并发量限制 (比如穿透时,端口猜测需要并发N多端口, 视频会议时,要和N多人同时收发包)
  跨地域的UDP速度波动,
白天晚上等不同时间,带宽浪费情况 
 不同512,1490等不同mtu丢包率等
等等这些,很多有经验的人, 几句话的事有助于大家选型, 不然直接拿了就用,后期全部弄下来,一个星期也够, 实际可能自己写的代码更简单一些

牢骚比较多,见谅,  作者可以不理会,  不想回,可以结贴了
