### ISSUE TITLE
Receiving a single message of size greater than (MTU - IKCP_OVERHEAD) * rcvwnd causes the receiver to get stuck forever

### ISSUE THREAD

**Issue by grandseiken** [skywind3000/kcp#140]
I might have got some details wrong, but my understanding from reading the code is: `ikcp_recv` can only return a received message when _all_ packets of the message have moved onto the receive queue. Since the receive queue is allowed to store at most `rcvwnd` packets, and each packet stores `MTU - IKCP_OVERHEAD` bytes of data, if you send a single message of size `(MTU - IKCP_OVERHEAD) * rcvwnd` bytes, the receiver will get stuck forever and never receive any more messages (while its receive buffer grows forever).

I am working around this by setting the `rcvwnd` to `255`, since a message is not allowed to be larger than `255 * (MTU - IKCP_OVERHEAD)` bytes anyway, but it was quite surprising.

**Comment by skywind3000** [comment]
That will never happen, rcv_wnd is for rcv_buf, fragment is within the rcv_queue. any arrival segment (fragment) will be moved from rcv_buf to rcv_queue soon if their sn equals rcv_nxt. So, rcv_buf will never get stuck no matter how big your message is.

But if receiver is busy, has no chance to invoke `ikcp_recv`, packets with SN outside range of [rcv_nxt, rcv_next + rcv_wnd] will not be accepted. So, as a result sender will stuck if receiver is busy, just like tcp.

**Comment by grandseiken** [comment]
Ok, like I said I might have misunderstood the details. But I have reproduced an issue like this. Can you explain the behaviour of the following test program?

The receiver is not busy, it always calls `ikcp_recv`; the sender does not get stuck, it keeps sending happily forever, but nothing ever gets through if `FAIL` is defined to `1`. Am I using the API incorrectly?

```c
#include <ikcp.h>
#include <stdint.h>
#include <stdio.h>
#include <unistd.h>

/*
set FAIL to 0: program outputs "successfully sent message N",
               "received message N with 44032 bytes" over and over
set FAIL to 1: program outputs "successfully sent message N",
               no messages ever received, memory use grows forever
*/
#define FAIL 1
#define MTU 1400
#define SNDWND 16
#define RCVWND 32
#define OVERHEAD 24
#define MSGSIZE ((MTU - OVERHEAD) * RCVWND + FAIL)

ikcpcb* sndr;
ikcpcb* rcvr;

int sndr_output(const char* buf, int len, ikcpcb* kcp, void* usr) {
  (void) kcp;
  (void) usr;
  return ikcp_input(rcvr, buf, len);
}

int rcvr_output(const char* buf, int len, ikcpcb* kcp, void* usr) {
  (void) kcp;
  (void) usr;
  return ikcp_input(sndr, buf, len);
}

int main() {
  char buf[MSGSIZE];
  int iter = 0, sends = 0, recvs = 0, res;
  /* simulated time */ uint32_t time = 0;

  sndr = ikcp_create(0, NULL);
  rcvr = ikcp_create(0, NULL);

  sndr->output = sndr_output;
  rcvr->output = rcvr_output;

  ikcp_setmtu(sndr, MTU);
  ikcp_setmtu(rcvr, MTU);

  ikcp_nodelay(sndr, 1, 10, 1, 1);
  ikcp_nodelay(rcvr, 1, 10, 1, 1);

  ikcp_wndsize(sndr, SNDWND, RCVWND);
  ikcp_wndsize(rcvr, SNDWND, RCVWND);

  while (1) {
    usleep(100);
    time += 10;
    ikcp_update(sndr, time);
    ikcp_update(rcvr, time);

    if (++iter % 10 == 0) {
      res = ikcp_send(sndr, buf, MSGSIZE);
      if (res) {
        printf("error: ikcp_send returned %d\n", res);
        return 1;
      } else {
        ++sends;
        printf("successfully sent message %d\n", sends);
      }
    }

    if ((res = ikcp_recv(sndr, buf, MSGSIZE)) >= 0) {
      printf("error: received unexpected message\n");
      return 1;
    }
    while ((res = ikcp_recv(rcvr, buf, MSGSIZE)) >= 0) {
      ++recvs;
      printf("received message %d with %d bytes\n", recvs, res);
    }
  }
}
```

**Comment by skywind3000** [comment]
BTW: what I mean "sender stuck" is that packages will get buffered in snd_queue, but you can check pending packages by `ikcp_waitsnd()`, and if it happens, you will see memory usage growing.

That is to say, kcp will never block your program, you must stop sending yourself when pending packages exceed some threshold.

**Comment by skywind3000** [comment]
fixed

**Comment by skywind3000** [comment]
update again.

**Comment by grandseiken** [comment]
Thanks for the quick response + fix, and thanks for the tip about `ikcp_waitsnd` (I could see from the source that KCP could not block, but wasn't sure what the intended way to do that was).
