### ISSUE TITLE
有没有将kcp移植到liteos系统上的？

### ISSUE THREAD

**Issue by Hoke** [skywind3000/kcp#142]
我们在手机和pc端移植的kcp效果很好，但liteos系统上效果很差，经常导致奔溃

**Comment by skywind3000** [comment]
程序没写对吧，纯算法的东西和具体哪个系统没关系啊。

**Comment by Hoke** [comment]
1.初始化是这样的：
ikcp_nodelay(kcpobj, 1, 10, 2, 1);
ikcp_wndsize(kcpobj, 128, 128);
ikcp_setmtu(kcpobj, 1400);
ikcp_setoutput(kcpobj, kcp_output);

2.ikcp_send 前面加了判断：
IUINT32 nwaitsnd = ikcp_waitsnd(kcpobj);
 if (nwaitsnd < kcpobj->snd_wnd) ｛
            //调用ikcp_send 
｝

3.ikcp_update 是每10毫秒调用一次，我在手机和pc端测试收发数据都很好，但在移植到liteos系统上，有时候一调用ikcp_update 或者ikcp_send就出现奔溃，而且这些地方都加了锁（因为在不同线程上）

**Comment by Hoke** [comment]
liteos下奔溃的地方是这个里：
static inline char *ikcp_encode32u(char *p, IUINT32 l)
{
#if IWORDS_BIG_ENDIAN
	*(unsigned char*)(p + 0) = (unsigned char)((l >>  0) & 0xff);
	*(unsigned char*)(p + 1) = (unsigned char)((l >>  8) & 0xff);
	*(unsigned char*)(p + 2) = (unsigned char)((l >> 16) & 0xff);
	*(unsigned char*)(p + 3) = (unsigned char)((l >> 24) & 0xff);
#else
	*(IUINT32*)p = l;//liteos系统在这里会奔溃，把这句改成memcpy方式就不会再奔溃了
#endif
	p += 4;
	return p;
}

这是liteos系统的原因，在ios和android，海思板子上没有出现这问题，这liteos系统还不成熟，
现在在liteos系统上用kcp效果很好，为韦老大点赞！

**Comment by skywind3000** [comment]
我跟你讲，我怀疑可能有多线程问题或者非法内存访问，memcpy只是将问题掩盖了。建议多检查
