### ISSUE TITLE
带宽和流量的关系

### ISSUE THREAD

**Issue by happyxgang** [skywind3000/kcp#144]
你好，我看readme上写的是多用10-20%的带宽。一开始以为会比tcp消耗更大的流量。

测试用例是每66ms发送一个50byte的数据包，在网络良好的情况下，kcp比tcp的流量甚至要更小一点，tcp头20字节，另外会有固定的10字节option的开销，又是可能在家sack的额外数据，kcp头为24byte，不计算往返的ack等控制数据包时，kcp每次传输的数据包更小。

在我的理解力带宽就是网络总的传输能力，多浪费的带宽就会导致传输相同数据的时间变长。加入带宽10mps，那么tcp假设可以全部利用就可以达到10m每秒的传输速度，而kcp大约为9m每秒。但是并不意味着kcp传输相同流量的业务数据时，消耗的流量比tcp多。请问是这样理解么？

还有是因为什么而消耗了带宽呢？

**Comment by skywind3000** [comment]
当丢包时kcp会更敏锐的重传

**Comment by caoli5288** [comment]
> 在我的理解力带宽就是网络总的传输能力，多浪费的带宽就会导致传输相同数据的时间变长。加入带宽10mps，那么tcp假设可以全部利用就可以达到10m每秒的传输速度，而kcp大约为9m每秒。但是并不意味着kcp传输相同流量的业务数据时，消耗的流量比tcp多。请问是这样理解么。

并不。所谓的浪费带宽，是指当链路上存在各种状况时，tcp因为更保守的流控和重发策略，可能峰值速度就能跑到1mbps，而kcp更激进的重发策略在链路状况不佳时可以获得远大于tcp的峰值速度（以及更低的延迟抖动），比较显著的特征是更低的RTO和fast_resend，这两者都会导致一些本来等等就知道可以不必要重发的包，白白发出去了，这就是浪费。

而当链路状况非常良好，tcp也能跑到最大速度时，重发是极少发生的，kcp也不会多浪费什么。而以现实互联网的链路状况tcp跑得比kcp快几乎是不可能发生的事情，更别说移动网，wifi，和跨境这几种场景了。

如果这样解释都看不懂的话，建议你至少了解下基本的网络协议知识吧。

**Comment by happyxgang** [comment]
@skywind3000 @caoli5288 thanks
