### ISSUE TITLE
kcp可以同时支持可靠和不可靠方式传输吗？

### ISSUE THREAD

**Issue by u3dkbe** [skywind3000/kcp#146]
比如我只开一个udp端口一个socket， 只是针对某些行为采取可靠数据发送或者不可靠的发送，kcp支持吗？

**Comment by skywind3000** [comment]
你自己都实现发送功能了，你不会在头部加一个字节，0就是裸udp，1就传送给kcp，函数结构是：

```C
connection->send(channel, data, size);
```

channel = 0 发送不可靠数据，channel=1 发送可靠数据，不就完了，关kcp什么事情啊？

**Comment by u3dkbe** [comment]
我只想知道kcp库是不是包含这2种方式， 不支持当然会自己做

**Comment by skywind3000** [comment]
不支持
