### ISSUE TITLE
请教一个kcp适用场景

### ISSUE THREAD

**Issue by l42111996** [skywind3000/kcp#148]
请教一个问题，做一款赛车类型的游戏，网络层用udp可能会跨洲际导致丢包率很高，业务角度允许部分丢包 有两种方案：
1，用udp每秒直接发30个包，丢了就丢了  然后bbr+tcp定时纠正位置
2，用kcp每秒发10个包
这两种方案哪种车的位置估计会好点？或者有更好的方案推荐吗？ 谢谢

**Comment by skywind3000** [comment]
方案3：混用裸的 udp + kcp

```c
connection.send(channel, pkt, size);
```

channel == 0 使用 kcp 发送可靠包，channel == 1 使用 udp 发送非可靠包。

因为传输是你自己实现的，你可以在发送UDP包的头部加一个字节，来代表这个channel，收到远程来的 UDP以后，也可以判断 channel==0 的话，把剩下的数据给 ikcp_input，否则剩下的数据为远程非可靠包。

这样你得到了一个新的发送函数，用channel来区别你想发送可靠数据还是非可靠数据。游戏里每秒钟继续30个包的非可靠，然后参杂一些可靠包，拆分下你的消息。

另，TCP+BBR表现在延迟方面比不过kcp，它只是比以前更合理的估计带宽了，不会像以前一样低估当前带宽，但是延迟方面还是那回事情，赶不上kcp，因为kcp的目标就不是合理利用带宽，而是烧带宽换延迟。网上有kcp vs bbr的评测，你可以搜索。

**Comment by l42111996** [comment]
谢谢您的解答
