### ISSUE TITLE
请问KCP返回的数据是基于流的还是基于数据报的？

### ISSUE THREAD

**Issue by codefell** [skywind3000/kcp#149]
开始以为是基于数据报返回数据，但是运行的test显示，会有2个报文在一起返回。
是否要应用层自己做分段呢？

谢谢！

**Comment by skywind3000** [comment]
基于数据报的，自己不用分段。

**Comment by codefell** [comment]
多谢！自己用c语言实现的test和kcp-sharp都没有问题，但是node-kcp看起来有点问题，会将许多报文一起返回，无论是作为客户端连C版本的server还是用C版本的client连node-kcp的server，都是如此，不知是不是哪块用的不对。。。
