### ISSUE TITLE
请问ikcp_input返回值为0，但是ikcp_recv返回-1是怎么回事？

### ISSUE THREAD

**Issue by woshi91** [skywind3000/kcp#150]
请问我项目中每成功接收到一个包之后，再来一个包ikcp_input返回值不为负数（为0），但是ikcp_recv返回-1是怎么回事？

每次都是
	if (iqueue_is_empty(&kcp->rcv_queue))
		return -1;

这是正常的吗？ 我是否判断ikcp_input只要成功， ikcp_recv返回-1就直接忽略呢？ 还是说我有bug？

**Comment by woshi91** [comment]
我不确定这种情况是异常还是正常

**Comment by flandrehuai** [comment]
我也这个情况我详细跟了一下发现
在ikcp_input （ikcp.c 813行） if (_itimediff(sn, kcp->rcv_nxt) >= 0)
的时候出现了问题然后数据就没有写进去

**Comment by skywind3000** [comment]
你们多线程访问同一个kcp对象？线程安全做好了没？

**Comment by woshi91** [comment]
单线程的哦

**Comment by woshi91** [comment]
我在if(ikcp_recv(**) < 0的情况下直接返回不做处理， 发现也能正常通信下去，这么说是正常现象？

**Comment by woshi91** [comment]
在发送端测试发现 一次ikcp_send 会有2次KCP->output产生， 第一次60字节服务器正常接收， 第二次24字节，就出现上面的情况。

kcp_output(const char *buf, int len, ikcpcb *kcp, void *user)

并且2次buf地址是一样的， len不一样，  服务器上对应的是第一次60字节正常接收， 第二次的24字节就返回recv -1

**Comment by skywind3000** [comment]
你自己没用对吧，第二次24字节output没准只是个 ack 包，或者某控制包，为何要反馈给上层？

**Comment by woshi91** [comment]
我现在没有反馈给上层， 收到ikcp_input返回正常0， ikcp_recv为-1就直接忽略了。


现在只是想知道这里返回-1的情况是不是正常 ，我应该直接pass？如您说的是ack等控制包那就是正常的， 是否我这里直接pass掉不做上层处理完事儿了

test例子里面是直接break了那个while
			// 没有收到包就退出
			if (hr < 0) break;

而asio-kcp在recv为-1的时候还加了print提示，如果有大量的ack和控制包则会产生大量的无用提示信息，是否asio-kcp这里处理不是很合适？

void connection::input(char* udp_data, size_t bytes_recvd, const udp::endpoint& udp_remote_endpoint)
{
    last_packet_recv_time_ = get_cur_clock();
    udp_remote_endpoint_ = udp_remote_endpoint;

    ikcp_input(p_kcp_, udp_data, bytes_recvd);

    {
        char kcp_buf[1024 * 1000] = "";
        int kcp_recvd_bytes = ikcp_recv(p_kcp_, kcp_buf, sizeof(kcp_buf));
        if (kcp_recvd_bytes <= 0)
        {
            std::cout << "\nkcp_recvd_bytes<=0: " << kcp_recvd_bytes << std::endl;
        }
        else
        {
            const std::string package(kcp_buf, kcp_recvd_bytes);
            std::cout << "\n" << last_packet_recv_time_
                << " conv:" << conv_
                << " lag_time:" << get_cur_clock() - last_packet_recv_time_
                << " kcp recv: " << kcp_recvd_bytes << std::endl <<
                Essential::ToHexDumpText(package, 32) << std::endl;
            if (auto ptr = connection_manager_weak_ptr_.lock())
            {
                ptr->call_event_callback_func(conv_, eRcvMsg, std::make_shared<std::string>(package));
            }
        }
    }
}

**Comment by skywind3000** [comment]
对，没有包直接退出。
