### ISSUE TITLE
请问ikcp_send正常情况下是立即发送还是会缓存到下一个tick呢？

### ISSUE THREAD

**Issue by woshi91** [skywind3000/kcp#151]
ikcp_send正常情况下是立即发送还是会缓存到下一个tick呢？
请问如果是缓存到下一个tick是出于什么考虑呢？（假设服务器压力非常小， 没有什么网络负载的情况下）

**Comment by skywind3000** [comment]
缓存到下一个tick是节省带宽，更好合包，tcp也是这么做的，不高兴你可以 flush啊。
