### ISSUE TITLE
请问项目发现有时ikcp_send之后10几秒才kcp->output有可能是哪里没设置对？

### ISSUE THREAD

**Issue by woshi91** [skywind3000/kcp#152]
请问项目发现有时ikcp_send之后10几秒才kcp->output有可能是哪里没设置对？

	kcp_ = ikcp_create((IUINT32)connid, (void*)this);
	kcp_->output = &Session::output;

	ikcp_wndsize(kcp_, 128, 128);

	ikcp_nodelay(kcp_, 1, 10, 2, 1);
	kcp_->rx_minrto = 10;
	kcp_->fastresend = 1;

// 大概一秒十次
ikcp_update(kcp_, ikcp_clock());

ikcp_clock直接抄test.cpp中的， win7系统

**Comment by woshi91** [comment]
是否是因为ikcp_nodelay设置的是10， 而update我是100调用一次而产生的问题呢？ 貌似也不是ikcp_clock能得出逝去的时间

**Comment by skywind3000** [comment]
会重复计时，不会有影响，这是算的相对时差，会循环计算的。你自己多调试下吧，我也不知道你程序写咋样了。

**Comment by woshi91** [comment]
请问我应该用master还是release最新版本呢？

**Comment by woshi91** [comment]
是不是我的ikcp_recv没有循环尝试多读的原因？还没测试，明天试试看

**Comment by haozia816** [comment]
我也遇到了，原因不明，不管ikcp_nodelay设置多少，会固定空闲10秒或20秒
