### ISSUE TITLE
ikcp_check ()函数中"seg 是 nullptr"的异常

### ISSUE THREAD

**Issue by glcolor** [skywind3000/kcp#168]
![exception](https://user-images.githubusercontent.com/1741084/43946659-6daef4c8-9cb8-11e8-8cee-b7ad683e4956.JPG)

调用Update的代码为:
```
void CKcpPeer::Update()
{
	IUINT32 tm = iclock();
	if (tm >= m_NextUpdate)
	{
		ikcp_update(m_Kcp, tm);
		m_NextUpdate = ikcp_check(m_Kcp, tm);
		//判断是否接收到数据
		int result = ikcp_recv(m_Kcp, m_Buffer, MAX_BUF_LEN);
		//如果有接收到数据，则调用回调函数
		if (result > 0 && OnDataArrived)
		{
			OnDataArrived(this, m_Buffer, result);
		}
	}
}
```
KCP对象的配置为:
ikcp_nodelay(m_Kcp, 1, 10, 2, 1);
m_Kcp->rx_minrto = 10;
m_Kcp->fastresend = 1;

程序的功能是发送一个64位的时间戳，接收方收到后原样返回，发送方以此计算延迟。
每次出现这个异常的时间不定，有时运行几秒即出错，有时运行数百秒才出错。
编译环境为Microsoft Visual Studio Community 2017 版本 15.7.5
运行环境为:Intel Core i5-7500，Windows 10 LTSB 2016 版本1607

请问是不是我的代码里面的ikcp_check使用方法有问题？

**Comment by skywind3000** [comment]
你是不是用了多线程？

**Comment by glcolor** [comment]
确实使用了多线程，发送和接收各使用了一个线程。
我去把这一块改一下，非常感谢！

**Comment by glcolor** [comment]
改成单线程之后，问题已经解决，感谢作者的帮助！
