### ISSUE TITLE
有个fec的问题请教一下

### ISSUE THREAD

**Issue by l42111996** [skywind3000/kcp#169]
参考go版本的fec设计，比如 dataShards 2 parityShardCount 1 ，我用在帧同步类型的游戏上面 以每秒固定帧发送数据，比如发送A,B,C 我看代码 发送A会缓存到fec的队列里面等待B到达后进行encode生成2个数据包和一个冗余包一起发送出去，这样导致不是一定的固定帧，A就会晚收到，如何解决这个问题呢？或者正确的方式应该是什么样子呢？

是不是fec更适用于允许部分丢包发包速率很快的场景？

**Comment by l42111996** [comment]
我想明白了  这里应该对A缓存并发送出去而不用等待，B也同样处理  并生成冗余包 ，生成的冗余包再单独发送就行了。

**Comment by skywind3000** [comment]
是这么回事情。

**Comment by l42111996** [comment]
有个问题，如果加了fec的话  如何去算rtt呢？  大概步骤是什么样子？   因为有些包是补出来的
