### ISSUE TITLE
KCP有没有纯python 实现的版本啊

### ISSUE THREAD

**Issue by luvjoey1996** [skywind3000/kcp#172]
如果有的话,想通过这个加深对网络协议的认识,是纯python !!!

**Comment by skywind3000** [comment]
不好意思没有，你可以写一个，我给你加链接。

**Comment by yukityan** [comment]
> 不好意思没有，你可以写一个，我给你加链接。

用cython包装了一下原生的C实现，也用纯python实现了一遍，然后用python aio简单做了一个端口转发的功能，可以申请加一下链接吗？ [https://github.com/yukityan/kcp-py](https://github.com/yukityan/kcp-py)

**Comment by enkiller** [comment]
纯 python 版本实现，不知道还需不需要

https://github.com/enkiller/pykcp

**Comment by luvjoey1996** [comment]
> 纯 python 版本实现，不知道还需不需要
> 
> https://github.com/enkiller/pykcp

66的
