### ISSUE TITLE
kcp上层做session如何判断连接是否断开？

### ISSUE THREAD

**Issue by l42111996** [skywind3000/kcp#176]
请教个问题，kcp上层做session判断连接是否连着的最佳实践是什么样子呢？  用超时时间？ 还是deadLink?，谢谢

**Comment by skywind3000** [comment]
下层判断ping超时吧。

**Comment by l42111996** [comment]
谢谢群主耐心解答。

**Comment by l42111996** [comment]
那kcp里面的deadlink字段设计的意义是什么呢?

**Comment by l42111996** [comment]
定期ping（比如一分钟启动一次）   这样时间会不会太长了？如何像tcp一样在大部分的时候断开连接会很快就知道。

**Comment by skywind3000** [comment]
你tcp没法很快知道，如果不发fin的话，比如你拔了网线，隔一会插上去，链接不会断。

**Comment by l42111996** [comment]
懂了，心跳来保证  如果主动断开可以发个断开消息。

**Comment by zwing1201** [comment]
> 

请问大神，这种心跳监测可以放在上层做吗？用kcp包ping，不用udp包。

**Comment by skywind3000** [comment]
@zwing1201  当然可以
