### ISSUE TITLE
ikcp_send 中 if (count == 0) count = 1; 设置的意义？

### ISSUE THREAD

**Issue by yanchuang12** [skywind3000/kcp#178]
求教 ikcp_send 中 if (count == 0) count = 1; 设置的意义在哪里， 按道理如果ikcp_send中计算的count=0时， 代表已经没有数据可发送了， 为什么还要重新设置count。

**Comment by yanchuang12** [comment]
看了这段代码不会走到

**Comment by CruiseYoung** [comment]
udp可以传输0字节的包
