### ISSUE TITLE
kcp做上层的ARQ是不是意味着很方便就可以做多网络聚合

### ISSUE THREAD

**Issue by HuHeng** [skywind3000/kcp#185]
在kcp发送回调中下层使用两个网络发数据,kcp的架构理念让双网络带宽聚合这件事变得简单了是吧.
不过有点不明白kcp->output这个回调的频率是根据用户设定的窗口来的吧,看文档好像窗口大小需要用户自行估计带宽并换算出来是吧

**Comment by caoli5288** [comment]
>  不过有点不明白kcp->output这个回调的频率是根据用户设定的窗口来的吧,看文档好像窗口大小需要用户自行估计带宽并换算出来是吧

1. 只管调用update就是了，output什么时候调用管不着。
2. 窗口大小是流控算法算出来的。
