### ISSUE TITLE
kcp同时收发数据是否安全？

### ISSUE THREAD

**Issue by ldcsaa** [skywind3000/kcp#190]
由于kcp API 没有提供锁机制，因此不能在多个线程中同时发数据（ikcp_send）或同时收数据（ikcp_input）。
由于recv通常是由网络事件触发的，而send数据通常是由程序或用户触发的。特别是对于Server应用，同时收发数据的场景很普遍。
我的问题是：
1、kcp能否同时收发数据（一个线程send，同时一个线程recv）？
2、ikcp_check/ikcp_update 这类函数是否线程安全，能否与ikcp_send/ikcp_read同时执行？
对于第一个问题，我的理解是：收发数据应该是两套独立的数据结构不会相互干扰，可以同时进行。

在此想得到一个确切的答案，谢谢~

**Comment by tsingson** [comment]
udp 两个端口, 一个发, 一个收.

**Comment by ldcsaa** [comment]
> udp 两个端口, 一个发, 一个收.

这跟下层UDP没有任何关系，是kcp内部数据结构的线程安全问题。

**Comment by skywind3000** [comment]
线程不安全，收发会相互影响内部状态
