### ISSUE TITLE
ikcp_check 使用疑问

### ISSUE THREAD

**Issue by ldcsaa** [skywind3000/kcp#193]
我的问题与 #138 一样，ikcp_check不可能返回大于interval的值，如何节省CPU？是不是应该这样使用，请指教：

```
while(10ms loop)
{
    current = clock();
    next = ikcp_check(current);

    // ！！重点！！
    if(current == next)
        ikcp_update(current);
}
```

**Comment by ldcsaa** [comment]
还有一个问题：kcp->updated 这个属性在第一次进入 ikcp_update() 时，它的值由 0 变为 1，以后就没有其他地方再修改它的值了，请问 kcp->updated 的作用是什么？

**Comment by halx99** [comment]
同问，楼主怎么使用的？
