### ISSUE TITLE
请教一个应用场景的问题

### ISSUE THREAD

**Issue by xy0058** [skywind3000/kcp#194]
打算通过卫星网络来传输文件，卫星链路带宽10Mbps，单个文件大小一般为1～3MB，单日数据量约10～20GB，做可靠传输，会一点对多点传输。卫星链路特点是高时延(500～600ms)，误码率其实并不高(10-7)，不选择TCP的原因是时延太大效率低。请问该应用场景选择KCP是否合适？感谢！

**Comment by necokeine** [comment]
根据我对KCP的了解，应该有点帮助，但是并不是特别合适。
1. 你并不需要真正意义上降低延迟，只是希望不要因为延迟导致TCP过度重传。
2. KCP虽然本意是在不可靠信道上做更低延迟的网络传输，如果线路时延就有500ms以上，但同时又没有太高的丢包率，更换并没有很多意义。
3. KCP的部分重传对你应该有许多帮助，但是不知道是否优势足够cover更换协议。
4. 我觉得你需要的更多是协议调整，可以考虑调整下参数？比如加大双方TCP的缓冲区，应该会有不小提升。
不好意思，我大概知道这些。FYI: Delay-Tolerant Networking

xy0058 <notifications@github.com> 于2019年3月18日周一 上午8:50写道：

**Comment by xy0058** [comment]
感谢您的热心解答，您说的很有道理，我会再认真权衡一下

**Comment by skywind3000** [comment]
不用实际编码，你可以直接用 kcptun 先试试，是否有提高。

**Comment by xy0058** [comment]
感谢！我上午又发现了一个有意思的协议UFTP，简介提到了特别适合卫星链路，只是是用UDP组播实现的，不知道对于网状网多点互传有没有影响，打算一并实验下。
