### ISSUE TITLE
Any idea for Obfuscate ?

### ISSUE THREAD

**Issue by netroby** [skywind3000/kcp#2]
Any idea for Obfuscate ?
We think about to using KCP  , but need more security (less resource usage, no much more cpu and memory usage)

**Comment by skywind3000** [comment]
There three level of protocol in our QuickNet project:
SESSION level: connection maintenance, handshake, RC4 encryption, better interface to end-point user
KCP level: ARQ
TRANSPORT level: FEC
NETWORK level: UDP, simple token xor encyption
----------------
These 3 different levels are arranged in sequence:
packets 'output' from upper level will invoke 'send' to lower level.
packets received from lower level will be input to the upper level.
---------------
RECOMMEND the RC4 algorithm in the SESSION level mechanism (upper level of KCP which use ikcp_send/ikcp_recv):
1. after connection established, a token must be exchange between both side, 
2. use it as RC4-key, encrypt data before call ikcp_send, and decrypt it when ikcp_recv returns. 
3. add an checksum to the session level packet's head (each level has their own header), after decrypt from ikcp_recv, if checksum value doesn't equal to the real one, shutdown the connection.

RECOMMEND simple 64 bit xor algorithm in NETWORK level (just before udp send) and verify another checksum and sockaddress from recvfrom

**Comment by skywind3000** [comment]
just like TCP implementation, only verify CONV in packet header, do encryption in upper level and sockaddr verify in lower level.

**Comment by netroby** [comment]
Thanks.

**Comment by xmudall** [comment]
@skywind3000 
Thanks for your recommendations. Two more questions:
1. Why does it need encryption in both session level and Network level?
2. RC4 has been prohibited in TLS for its weakness in 2015. Is there any other efficient encryption algorithm instead?
