### ISSUE TITLE
ikcp_recv内部断言失败？

### ISSUE THREAD

**Issue by tzraeq** [skywind3000/kcp#207]
ikcp_recv方法里有这么一句代码，assert(len == peeksize);，这两个变量都是ikcp_recv内部计算出来的，怎么会失败呢？

**Comment by skywind3000** [comment]
你是不是多线程操作 kcp 对象？

**Comment by tzraeq** [comment]
抱歉这么久才回来，确实，之前是多线程操作同一个kcp实例。
