### ISSUE TITLE
关闭重传的功能如何实现

### ISSUE THREAD

**Issue by coderchou** [skywind3000/kcp#215]
大佬，我现在是传输视频数据，只要处理好乱序和分片的问题，不想要启动丢包重传的功能，这个设置应该如何实现

**Comment by coderchou** [comment]
ikcp_check()函数应该如何调用

**Comment by coderchou** [comment]
有大神能帮我解答一下吗

**Comment by majianwei0705** [comment]
感觉有些浪费了，分片和乱序自己写代码解决多好

**Comment by coderchou** [comment]
> 感觉有些浪费了，分片和乱序自己写代码解决多好

好的，现在已经自己实现分片了，乱序的问题未出现
