### ISSUE TITLE
ikcp_recv 一直返回 -1

### ISSUE THREAD

**Issue by zhaokaixs** [skywind3000/kcp#22]
不知道是什么情况，在收到第一个正确的包后，接下来的包 一直返回-1.
是我发的太频繁了么？

**Comment by skywind3000** [comment]
没有正确发送过来，这边没有数据，所以返回-1（EAGAIN），能不能先看看test是怎么写的，先跑一下再说啊？

**Comment by zhaokaixs** [comment]
是照着例子做的,, 可能是我调试的时候 打断点了,, 
还一个奇怪的问题，跑一会，就崩在了
ikcp.c  960行, 
	// flush data segments
	for (p = kcp->snd_buf.next; p != &kcp->snd_buf; p = p->next) {
		IKCPSEG *segment = iqueue_entry(p, IKCPSEG, node);//空指针
		int needsend = 0;
		if (segment->xmit == 0) {

麻烦您了

**Comment by skywind3000** [comment]
我觉得你进程的内存被破坏掉了。

**Comment by zhaokaixs** [comment]
我现在也找不到问题的所在了, 都是崩在// flush data segments里，出现了空指针，我也不知道为什么, 
  我照着test例程做的，只不过 我单独开了一个线程 做update, 发送比较频繁，每包数据都在1300左右, 发松了一会就崩了，都是内存访问的问题,实在摸不清头脑了

**Comment by skywind3000** [comment]
你多线程干嘛？一个连接放倒一个线程即可，莫非你还多线程处理kcp了？加锁没？

**Comment by zhaokaixs** [comment]
@skywind3000 是这样的， 底层UDP网络引擎 是IOCP多线程的，在OnRecive接口 我调用的咱们的kcp_input,kcp_recv,      然后在发送队列线程调用的kcp_send,, 因为要对h264数据分包， 然后又单独开了一个线程 做kcp_update,, 你说加锁的问题，，， 我都没加锁,,, 难道要所有调用都要加锁吗。，。。

**Comment by skywind3000** [comment]
多线程用当然要加锁啊

**Comment by WJunB** [comment]
@zhaokaixs 哥们 你的kcp_recv不到数据的问题解决了么？我也是这个问题。

**Comment by WJunB** [comment]
@zhaokaixs 解决了git上传份代码呗。 大家能学习学习。

**Comment by huyuguang** [comment]
很显然应该在同一个thread里调用所有的ikcp_xxx，不同的kcp实例可以在不同的thread里。你用iocp则应该利用iocp的WaitQueueComptionPort的最后一个参数timeout来做update。如果你非要新起一个thread来做timer，那么在timer里调用PostIocp，唤醒你的WaitQueueXxxx。

**Comment by WJunB** [comment]
@huyuguang 问题解决了。不小心多线程使用kcp了。没有仔细看！谢谢～ 
我在点对点传输udp的时候是可以加kcp的。换成AtoB，BtoC的时候。AtoB部分，B收到数据不能正确ikcp_input。错误原因是conv不一致。我debug查了下A和B的kcp->conv值是一样的。传输过程中数据也没有发生改变。A encode 之后 在B做decode conv值变了。  `ikcp_creat(0x11223344,(void*)1)`。conv创建的时候一样的，user不同。
