### ISSUE TITLE
什么情况下KCP会丢包？怎样设置才能让KCP不丢包？

### ISSUE THREAD

**Issue by tzraeq** [skywind3000/kcp#230]
如题，经过测试，我发现KCP也不能100%的保证数据传输的正确性。发生的情况是，数据长度是70000的时候，mtu设置成470，互联网传输。配置如下。
```c
ikcp_wndsize(kcp, 1024, 1024);
ikcp_nodelay(kcp, 1, 10, 2, 1);
kcp->rx_minrto = 5;
```

**Comment by tzraeq** [comment]
现在没有多线程操作了，我收到kcp的包都放到队列里，然后另外一个线程loop，取队列，kcp_input，然后kcp_recv，然后kcp_update，然后下一次loop。我的业务包是有连续的序号的，从接收端recv出来的数据来看，业务包的序号在突然有大量数据的时候就会跳包。请问我应该从哪个地方入手去调试这个事儿？

**Comment by skywind3000** [comment]
不好意思，帮不了你，你程序的事情得你自己看。
