### ISSUE TITLE
请问一下使用kcp在应用层ikcp_recv收到包是否是完整包？需不需要自己做粘包拼包？

### ISSUE THREAD

**Issue by kcpnewly** [skywind3000/kcp#238]
请问一下使用kcp在应用层ikcp_recv收到包是否是完整包？需不需要自己做粘包拼包？

流模式和包模式下？

比如分别在这2种模式下， 我发送一个1M的包， 我kcp_input之后， ikcp_recv得到的是否是一个1M的完整包？

**Comment by skywind3000** [comment]
包模式下，自己不需要粘包，发送1M，接收也是 1M，流模式下发送 1M，会接收到好多个小包。

**Comment by kcpnewly** [comment]
继续请教一下， 比如做一个视频流推送服务， 每帧画面可能包较大， 这种情况是包模式好还是流模式好呢？

**Comment by skywind3000** [comment]
默认的包模式即可
