### ISSUE TITLE
conv应该怎么生成？比如有大量的客户端向服务端建立通信，客户端如何生成唯一的conv？

### ISSUE THREAD

**Issue by kcpnewly** [skywind3000/kcp#240]
conv应该怎么生成？比如我一组服务器上的进程会相互互联，这样他们可能产生相同的id， 并且持续可能根据情况动态增加进程, 给每个进程设死一个区段好像也不是很方便

如果是64位ID就可以使用时间戳加累加数来动态产生ID，但conv是32位的， 有什么好方法呢？

**Comment by skywind3000** [comment]
conv：高15位保存客户端的 kcp 对象数组索引，低15位保存服务端的kcp对象数组索引，剩下两位校验一下，服务端和客户端的数组索引可以再连接握手的时候交换。

**Comment by kcpnewly** [comment]
意思是我弄个id分配进程？ 所有其他进程都请求这个进程分配conv？


如果每个进程都自己生成自己的顺序生成是不是就可能导致id冲突了？比如a、b、c3个进程互联， a用conv=1去连c， b也用了conv=1去连c， c里面就有2个conv为1的session。


或者按照asiokcp的办法反过来做， a和b都是请求和c握手， c分配了1和2的conv和他们通信， 假如c又需要连d进程， d进程分配了conv=1和c通信， c还是可能有多个conv=1的冲突。

**Comment by l42111996** [comment]
按照asiokcp的办法反过来做， a和b都是请求和c握手， c分配了1和2的conv和他们通信， 假如c又需要连d进程， d进程分配了conv=1和c通信， c还是可能有多个conv=1的冲突。

这里c对于a和b是服务器端   c对于d是客户端   客户端和服务器端的回话保持的那个map是不同的实例

**Comment by skywind3000** [comment]
conv 只应该是一个随机数，用来验证包合法用的，不一定非要作为 kcp 对象实例的 key 来检索，至于服务端和客户端两边的 key ，可以在 kcp->output 的函数中，实际发包时，每个包前面加一个 `srcindex` 和 `dstindex` 前者是客户端的 key, 后者是服务端的 key，建立连接的过程中，两边分配了 kcp 对象以后主动交换两边的 index，然后以后每个包都会带上。

那么收到包的时候就可以根据 index 找到本地的 kcp 对象，然后再对比 `conv` 是否一致，你可以理解成 tcp 的 `端口` 其实也是这样一个用于检索的虚拟概念。

**Comment by jxjlimi31** [comment]
你可以理解成 tcp 的 端口 其实也是这样一个用于检索的虚拟概念。 如果是端口的概念，那可以确定一个值就行了。没必要在简历映射关系吧？
