### ISSUE TITLE
KCP control object is bi- or unidirectional?

### ISSUE THREAD

**Issue by nxrighthere** [skywind3000/kcp#244]
I've encountered a problem recently where the KCP control object works fine but only in one direction, as soon as I'm trying to send/receive using the same control object, eventually packets no longer arrive properly at both ends. So my question is, the KCP control object is bi- or unidirectional?

**Comment by nxrighthere** [comment]
It seems that I've solved the problem, it was an issue in logic on top of KCP.

**Comment by skywind3000** [comment]
Beware, the kcp control object is not thread-safe, don't use one instance in different threads without lock.

**Comment by nxrighthere** [comment]
Yes, I'm aware of that, thanks.
