### ISSUE TITLE
Android中应用无法回传ack

### ISSUE THREAD

**Issue by GadusBetter** [skywind3000/kcp#245]
我的需求是Android APP通过kcp将音视频数据发送到同一局域网下的其他Android手机上，现在我发送端能正常发送（数据流无法确定是否正确），在接收端接收到数据后无法正常组包，查看资料说还需要回传ack，请问ack是需要接收端再次通过udp将收到的包再以IKCP_CMD_ACK的cmd发送给发送端吗

**Comment by skywind3000** [comment]
请仔细看文档和示例，检查下你少了啥。

**Comment by GadusBetter** [comment]
请问哪里有安卓的应用实例和文档，目前没找到资料来确定步骤是否正确呢

**Comment by skywind3000** [comment]
test.cpp，这是夸平台的和平台无关。你两边都设置 output 函数了没？你接收方即使不发数据也有定时的控制命令需要传递给发送方，你正确发送过去了么？

**Comment by GadusBetter** [comment]
我知道这是跨平台的  主要是现在我没办法确定我是哪里出的问题，接收和发送端的output函数作用是一样的吗？我看都是在发送数据，是不是我单纯的一端只接收 一端只发送的话有一端的output下是不用执行发送操作的？

**Comment by skywind3000** [comment]
怎么可能另外一端 output 不用执行，你怎么理解的？

**Comment by GadusBetter** [comment]
两个安卓手机  一个只负责发送 一个只负责接收，接收端在outpot里也需要执行send操作吗，如果是的话这里执行send是在处理什么工作？回传确认包吗？

**Comment by skywind3000** [comment]
自己多看看 test.cpp 吧，又不能具体指出代码里面哪行错了，又不能提供最小重现方式。我提供的文档已经很丰富了，大家好好看都能做得出来，你这样光凭嘴讲，还不能精确描述，我很难给你解答，这是要我帮你检查代码么？也行，付费咨询，我可以帮你看代码。

**Comment by GadusBetter** [comment]
这是检查代码？？？这是就你写的代码流程提出点不解之处，哪句话说了让你给检查代码了，看不到issue里有多少问你其他语言的实现方式，就是因为对c不是很熟悉才问呢，要是都能看懂我还懒得问你呢，动不动就付费，垃圾玩意

**Comment by skywind3000** [comment]
成语 “恼羞成怒” 说的就是你这种情况，开源项目咨询收费天经地义的事情。

你要反馈代码问题，请你具体点指出来代码哪里有问题，那么多文档和示例情况下你要咨询怎么用，简单几句我也就给你说了，但是从你提问第一句到最后一句，我发现你都没看过或者理解 test.cpp 里面 kcp 对象到底是怎么用的，连接两端的数据到底是怎么收发的。

在这种情况下，显然一两句话的回复你是没办法弄明白的，你需要的是系统的讲解，明白？这是要费专门时间的，明白？
