### ISSUE TITLE
请问ikcp_waitsnd这个函数应该怎么用的？当我想要知道我发送的数据是否完全发送给对方的时候。

### ISSUE THREAD

**Issue by wingpuiLaw** [skywind3000/kcp#251]
调用ikcp_waitsnd以后，应该再调用什么函数去更新下次查询ikcp_waitsnd的值？

**Comment by skywind3000** [comment]
如果上层调度了 ikcp_input 或者 ikcp_flush ，那么可以再次查询 ikcp_waitsnd

**Comment by wingpuiLaw** [comment]
那可以这样写吗？可是我这样写的话，等while都结束了以后，对方依旧还有几个包还没有收到呢？需要多调用几次flush()。是用法有问题？还是可能是其他地方没写对？
`
while (ikcp_waitsnd(pKcp) > 0) {
  current = iclock();
  ikcp_update(current);

  next = ikcp_check(current);
  usleep(1000*(next - current));

  ikcp_flush();
}
`

**Comment by skywind3000** [comment]
完全错误，异步网络应该怎么写你好像没研究过？永远不能等待任何一个连接的数据，对方一直不收怎么办？你打算死循环么？普通异步 tcp 网络 socket发不出去怎么办？你没处理过么？

**Comment by wingpuiLaw** [comment]
以前的确没写过非阻塞异步网络。哦~你的意思是说ikcp_waitsnd只保证缓存中的消息都从队列里面调用下层发送函数了，但是不检查una吗？

**Comment by skywind3000** [comment]
。。。。。。

**Comment by wingpuiLaw** [comment]
好的，感谢。我待会认真看下异步网络模型。我现在暂时把发送端代码改成这样，就可以保证发送端完整接收数据才结束了，不过还没弄懂原理--!，也没发现会有什么问题……
``` C++
#define MAX_TIMEOUT 20
int times = 0;
while ( (pKcp->xmit > ikcp_waitsnd(pKcp)) && (times++ < MAX_TIMEOUT) ) {
  current = iclock();
  ikcp_update(current);

  ikcp_fulsh();

  next = ikcp_check(current);
  usleep(1000*(next - current));
}
```
