### ISSUE TITLE
How to determine conv

### ISSUE THREAD

**Issue by GlassBeaver** [skywind3000/kcp#255]
Hi, how are two endpoints supposed to know what conv to use?
I can imagine the following scenarios:

1. Computer A connects to computer B on a fixed conv, let's say conv=0. B responds to A with a free conv channel. If the same conv is free at A, it accepts, otherwise it proposes a new one. Repeat until a free conv is found.
2. Computer A connects to B via TCP, they negotiate a conv and switch back to UDP using it.

What is the recommended approach?

**Comment by skywind3000** [comment]
TCP uses conv just as a **confirmation**, one conv represents one session. the packets without different conv will be simply discarded by tcp.

TCP does not use `conv` as an index of a object dictionary, and `conv` is not designed for this.

TCP uses `port`, to be specific `dstport` and `srcport`, to indicate object location for each peer.

So does kcp.

**Comment by GlassBeaver** [comment]
Thanks for the very prompt response. I might be misunderstanding what kcp is for. I have a p2p multiplayer game where players find each other via a central matchmaking server that does NAT punchthrough for them. I'm not using anything on top of kcp, I don't have a "transport layer", it's just kcp on top of UDP sockets and my custom code that groups UDP packets into game messages. Is there an additional layer I should be using?

**Comment by skywind3000** [comment]
You should introduce another layer, for:

1. hand shaking
2. session identification (locate kcp object in each peer)
3. encryption
4. fec (maybe you need this in the future).

A network **stack** is comprised of many layers, each layer has a transport unit, given transport units stack together in certain order become **protocol stack**.

It has been discussed in:

https://github.com/skywind3000/kcp/wiki/Network-Layer
