### ISSUE TITLE
server有时候会crash，kcp用的最新版本1.5

### ISSUE THREAD

**Issue by dantezhu** [skywind3000/kcp#256]
(gdb) bt
#0  0x0000000000414638 in ikcp_input (kcp=0xee1300001f000000, data=0x2561538 "\001", size=48) at src/../require/kcp/ikcp.c:751
#1  0x0000000000418dbe in maple::BaseKcpConnection::inputMessage (this=0x25912b0, buf=0x2561538 "\001", size=48) at src/BaseKcpConnection.cpp:102

也不是每次请求都crash，但是每天会有那么几个core文件。
ikcp_input的data我确认是没有越界的，在堆上固定分配了65535的大小。

环境是 centos 7.5 x64， kcp 版本是1.5。
我们的用法是用的epoll + kcp_check的方式，能否麻烦给一下可能的问题的思路？我去检查一下。

**Comment by skywind3000** [comment]
https://github.com/skywind3000/kcp/blob/87c0e6a92bb7d8b49937522cdd5844905d58d8e6/ikcp.c#L751

751 行就是读取一个 kcp 变量的值，这如果出错的话，说明你整个 kcp 对象坏掉了，会不会是你多线程里操作同一个 kcp 对象没加锁，或者哪里释放掉了？又调用 ikcp_input，又或者哪里野指针破坏了？

**Comment by dantezhu** [comment]
@skywind3000 好的多谢。我们是用的单线程，我先再去检查一下代码。

**Comment by skywind3000** [comment]
我看你的 kcp 对象地址很奇怪：

    kcp=0xee1300001f000000

怎么会有这么高位的地址？堆分配都是从比较低的地址分配，你看你其他几个对象地址：

    this=0x25912b0
    data=0x2561538 

这种地址才是正常的值。

**Comment by dantezhu** [comment]
@skywind3000 ，非常感谢，原因已经定位，果然是出现了野指针。
我们目前的做法是将将connections以addr为key做成map，之前connection回收之后忘记清空对应的addr的map中的connection了，所以当addr被复用的时候，就会异常。

另外正好顺便问一下，我们kcp初始化传入的conv全都是同一个固定值，因为建立kcp连接前并没有做额外的客户端与服务器的通信协商，这样的写法是否有什么风险？还是说是ok的？

**Comment by skywind3000** [comment]
你们的项目，你们自己研究吧，多看看项目 wiki

**Comment by dantezhu** [comment]
@skywind3000 明白，多谢
