### ISSUE TITLE
請教多人fps遊戲應用場景的問題

### ISSUE THREAD

**Issue by fnaith** [skywind3000/kcp#260]
網上很多建議是，玩家的位置要用udp傳送，因為丟包的資料沒那麼重要，不需要tcp的重傳機制。

但是不確定kcp是不是快到能無視重傳時間，想請問作者認為基於udp的kcp適不適用這種場景？

我還想過給kcp加個失敗時是否重傳的參數，之類的方案，但是總感覺越整越複雜。想請作者指點。

**Comment by fnaith** [comment]
抱歉，我剛翻到[舊Issue單](https://github.com/skywind3000/kcp/issues/148)，應該是一樣的問題。

感覺UDP混用的疑問以後會越來越常出現，畢竟ＫＣＰ真的是越來越火，看看作者願不願意寫一段說明進readme吧。

**Comment by skywind3000** [comment]
https://github.com/skywind3000/kcp/wiki/KCP-Best-Practice

wiki 里面有写。

**Comment by fnaith** [comment]
瞭解了，感謝您！
