### ISSUE TITLE
请问一下ikcp_recv()中这一段代码是否可以删除

### ISSUE THREAD

**Issue by zhangboyang** [skywind3000/kcp#261]
你好，我正在把kcp改成“kcp从应用层拉取要发送的数据、kcp将收到的数据推给应用层”的形式。在读代码的过程中，我认为ikcp_recv()中这一段代码可以删除。因为ikcp_parse_data()已经进行了完全相同的处理。求问我的看法是否正确？谢谢～
https://github.com/skywind3000/kcp/blob/53e568bd3b9cf431a29cd41944cfea1f621222bf/ikcp.c#L413-L425

**Comment by skywind3000** [comment]
我建议你不要改，乱改改出问题来的，你的这个需求可以在 ikcp_input 以后里面 while 循环 ikcp_recv 直到没有包，一旦受到包就调用上层的回调。不就行了么？别一点小事都要想着改第三方的东西，这只会引入麻烦，未来我升级你要不要每次 merge ？你没修改过的代码我可以给你保证质量，那么多第三方的 kcp 衍生项目都帮你验证过了，你修改后，碰到问题到底是我的还是你的？

**Comment by zhangboyang** [comment]
当我第一句话没说，你看一下你这段代码是否是冗余的，要不要考虑删除

**Comment by zhangboyang** [comment]
你误会我意思了，我就是想提个pull request，内容是删掉这段代码

**Comment by skywind3000** [comment]
我晕，你怎么读的代码当然不能删除，rcv_queue 是有大小控制的，你应用层如果不一直 ikcp_recv，那么 rcv_queue 会满，然后导致远端无法向你发送信息。如果 rcv_queue 已满，ikcp_parse_data 就不会转移数据过去，那么如果后面没有包 input 进来，就不会触发 ikcp_parse_data，就不会继续给 rcv_queue 追加内容，那么你 ikcp_recv 消耗完了 rcv_queue 里面的数据，下面又被你删掉的话，你就会碰到明明有数据在 rcv_buf 已经准备好了，可是你却拿不出来的情况。

**Comment by zhangboyang** [comment]
哦哦，明白了，谢谢
