### ISSUE TITLE
ikcp_recv 第二次启动程序一直等于-1

### ISSUE THREAD

**Issue by xhzth7091** [skywind3000/kcp#262]
我写了一个视频 推流 和 拉流 ,用kcp来连接。   
2端可以正常播放，但是 当我把  拉流  的这端的程序给杀死以后，  推流  这端继续推流，  拉流这端重新打开，连接kcp，代码如下:
           c_kcp = ikcp_create(6, NULL);
           c_kcp->output = c_udp_output;
            ikcp_nodelay(c_kcp, 1, 10, 0, 1);//可以收到图像
            c_kcp->rx_minrto = 10;
            c_kcp->fastresend = 1;
            ikcp_wndsize(c_kcp, 128, 128);
            ikcp_setmtu(c_kcp, 1400);

ikcp_update用定时器启动，我udp收到消息以后 ikcp_input=0,ikcp_recv一直等于-1，这个需要怎么处理，   我推流的 那端 用ikcp_waitsnd设置了最大的阀值，超过就不会再调用ikcp_send，求教

**Comment by skywind3000** [comment]
请你不要告诉我，两个进程通信，一边断了重连，另外一边你还在用老的 kcp 对象和它通信。

**Comment by shaoyuan1943** [comment]
new connection, new kcp

**Comment by xhzth7091** [comment]
那我断掉的一端的情况下，2端都要ikcp_release  kcp的对象？
2端都要重新c_kcp = ikcp_create(6, NULL);创建？  
 kcp有没有办法知道有一端断掉连接了？

**Comment by skywind3000** [comment]
当然，内部状态都不一样了，还期待他们能配对工作么？

**Comment by xhzth7091** [comment]
那是不是要先ikcp_flush，在ikcp_release以后，  在ikcp_create新的kcp

**Comment by skywind3000** [comment]
你都断线了还 flush 什么？

**Comment by skywind3000** [comment]
这是你自己使用问题，关闭了
