### ISSUE TITLE
iOS 使用kcp 在回调c_udp_output方法里接受data数据 ，会偶发增加一倍现象

### ISSUE THREAD

**Issue by xiejicangxjc** [skywind3000/kcp#267]
点击发送按钮，调用下面的代码，同时启动一个定时器，每三秒钟也执行一次下面的代码，(ikcp_update)这个方法20毫秒调用一次。
 NSString *msg = @"send";
    NSData *sendData = [msg dataUsingEncoding:NSUTF8StringEncoding];
    int video = ikcp_send(c_kcp,  sendData.bytes, (int)sendData.length);
只是发送了四个字节的数据，
发送完毕之后，程序会不断的执行 c_udp_output方法，在方法内执行下面的代码
NSData * data = [NSData dataWithBytes:buf length:len]; 
  NSLog(@" data.length == %lu",(unsigned long)data.length);
会偶发data.length 增加一倍的情况，一秒钟之内会出现3-7次增加一倍的情况

**Comment by skywind3000** [comment]
你自己看看代码去，双方通信又不是只有 data，还要 ack 还有窗口探测消息。连接新建立，初始的 rto 较小，当然会更容易超时重发，几次以后，rto 会逐渐变长。况且你这个是只有单边，真实双方通信，rto会被迅速探测出来。

**Comment by xiejicangxjc** [comment]
我说的意思是，send的data数据是一成不变，写死的数据，在c_udp_output 这个回调里面接受data数据，会偶发增加。

**Comment by skywind3000** [comment]
谁跟你说 output 函数的数据尺寸就要和 send 一致呢？

我上面不是跟你说了么，窗口探测命令，也需要发送，而 output 出来的东西是打包数据，又不是光有你 send 的东西，可能还会包括其他。

**Comment by skywind3000** [comment]
多看看代码，理解到位再提 issue 吧。
