### ISSUE TITLE
请教一个流量问题

### ISSUE THREAD

**Issue by l42111996** [skywind3000/kcp#273]
我用kcp和tcp对比进行帧同步场景测试
3000个客户端:50ms发送一次数据，每个包数据20字节
服务器:8客户端组成一个房间，收到数据放入房间缓存，每50ms将收到的8个人的包合并分别发给这8个人
监测服务器流量:
tcp： in:36.26Mbit/s  out:111.25Mbit/s
kcp:   in:69.57Mbit/s  out:133.45Mbit/s

这个流量正常吗？   为什么in的流量比tcp大这么多？  我有统计重发率，没有发现有重发

**Comment by skywind3000** [comment]
正常的，因为每次往外发送都有 kcp 包头和 udp/ip 包头，加起来比 tcp/ip 包头要大，因此当包比较小的时候，包头的占用比例就会比较大，你服务器往外发的时候，数据体比较大，包头比例自然小。

还有一个情况是 tcp 可能会归并你的两分数据，一个包发出去，造成流量下降，但是延迟上升的情况。

优化方式是，数据归并发送，但是如果你就是需要保证实时性的话，拿就这样了。
