### ISSUE TITLE
连接中途，ikcp_recv收不到数据

### ISSUE THREAD

**Issue by dai-2584** [skywind3000/kcp#278]
刚开始的时候，有几个kcp对象运行接收数据正常，后面就突然收不到数据了，看日志 ikcp_recv函数返回分别：-1、 -2、 -3
kcp设置如下：
0x170b3f0 = ikcp_create(965809981, 0x170b2a0)
ikcp_wndsize(kcp, 512, 512)
ikcp_nodelay(kcp, 1, 10, 3, 1)
pLink->m_pKcp->rx_minrto = 30)

**Comment by dai-2584** [comment]
服务器端的设置也是：
ikcp_wndsize(kcp, 512, 512)
ikcp_nodelay(kcp, 1, 10, 3, 1)
pLink->m_pKcp->rx_minrto = 30)

**Comment by dai-2584** [comment]
-2 = ikcp_recv()
经常返回-2，不知道正常不？

**Comment by skywind3000** [comment]
-2 代表没数据，EAGAIN/EWOULDBLOCK 了，等会再试

**Comment by dai-2584** [comment]
但是明明input了数据了，一直返回-2：
m_strDebugDstIp= 42.186.121.65, 0 = ikcp_input(1414)
m_strDebugDstIp= 42.186.121.65, -2 = ikcp_recv()
m_strDebugDstIp= 42.186.121.65, -2 = ikcp_recv()

**Comment by skywind3000** [comment]
input 的数据不够多吧，比如一个数据包被分成了两个 udp 包。看下 rcv_buf, rcv_queue 的长度你就知道了。

**Comment by dai-2584** [comment]
一言惊醒梦中人，谢谢大牛！
