### ISSUE TITLE
在Windows系统上运行会导致内存页错误page fault in nonpaged area

### ISSUE THREAD

**Issue by XuJianxing** [skywind3000/kcp#280]
最开始我是在Windows系统上测试的代码，服务端使用Python封装后的Kcp，客户端使用C#版的Kcp相互发消息，结果程序一运行就会导致黑屏然后重启。我感觉是系统环境的问题，我又使用linux系统测试之后发现可以正常运行。
但是不知道Windows系统中为什么会出现问题？求解答

**Comment by skywind3000** [comment]
肯定是你写出 bug 来了呗，用多线程了么？加锁了么？内存处理正确了么？

**Comment by XuJianxing** [comment]
都是单线程下运行，也没做过内存操作，python和C#都是自动管理内存了，只在两端用不同语言封装后的recv和send方法做简单的收发，就是同一份代码不同系统下运行的，结果Windows上会出错linux上不会。但是用同一语言封装的代码做收发也不会出错。搜了一下page fault in nonpaged area这个错误可能和Windows的虚拟内存有关，其他就不懂了。。希望有经验的或者遇到同样问题的人可以解答一下...

**Comment by skywind3000** [comment]
如果你觉得 kcp 引起的崩溃情拿出确切的最小化重现方式和栈帧信息，否则我也帮不了你
