### ISSUE TITLE
sn问题

### ISSUE THREAD

**Issue by lbit20131014** [skywind3000/kcp#284]
@skywind3000 大佬，先请教一个问题，客户端和服务端通信，如果sn发送到10了，这个时候关闭客户端重启，重新和服务端通信，次数sn会从0开始，但服务端会将小于rcv_nxt的报文丢弃，是不是有这个问题？还是我使用有误，请指教

**Comment by skywind3000** [comment]
重新连接，服务端要创建新的 kcp 对象，难道你觉得 tcp 断线重连服务端还会用原来的老的 tcp 控制对象来配对么？
