### ISSUE TITLE
底层UDP的连接管理几点问题 请教下

### ISSUE THREAD

**Issue by sgf** [skywind3000/kcp#286]
底层UDP协议 尤其是遇到NAT的情况。
若是做连接管理的话。若是仅用UDP的 IP+端口号 从而标记客户端进行session管理可靠么？
是不是要做心跳 维持NAT的端口映射？比如让客户端每5秒发一次包。
这样做保险么？
有没有经验丰富的大佬谈谈 这方面的心得体会。

**Comment by skywind3000** [comment]
NAT 映射当然可靠，不然所有 UDP 的程序都要挂了，半分钟一次心跳即可。

**Comment by sgf** [comment]
感谢作者耐心解答
