### ISSUE TITLE
Is there a way of detecting timed out connections?

### ISSUE THREAD

**Issue by andersc** [skywind3000/kcp#287]
How do you detect if a client stopped sending data. Since UDP is connection less I guess KCP has/should to provide a notification that a connection timed out after a certain amount of time.

I might have missed this any help is appreciated. 

/A

**Comment by sgf** [comment]
im a noob,but its seems there is a deadlink (timeout to detect link is dead).

**Comment by andersc** [comment]
@sgf Thanks for your answer. I did block all packets from my server/listener after my first successful packet transmission and every time I did a `ikcp_update` I also checked the _dead_link_  and _state_ on both the sender and server/listener.  _dead_link_ was constant reading 20 for both sides and _state_ is always 0.

**Comment by andersc** [comment]
I solved it by implementing a heartbeat monitor above of KCP -> https://github.com/Unit-X/kcp-cpp

**Comment by sgf** [comment]
heartbeat  is necessary.
In a NAT environment, if there is no heartbeat, Nat maps to cancel the client's UDP port.
