### ISSUE TITLE
Thread safety 

### ISSUE THREAD

**Issue by andersc** [skywind3000/kcp#288]
Should I mutex all calls to KCP or are some/all methods thread safe?

**Comment by NobodyXu** [comment]
I briefly looks through `ikcp.h` and `ikcp.c` and it seems that there is neither locking nor atomic used in the project.

So yeah, you probably needs to mutex calss to kcp.

**Comment by andersc** [comment]
Yes I kind of get that impression also. Thanks for the answer.
