### ISSUE TITLE
Time counter is 32-bits

### ISSUE THREAD

**Issue by andersc** [skywind3000/kcp#290]
If you use KCP for long term connections the 32-bit millisecond counter will wrap after 47 days is that a problem? should that be changed to a 64-bit counter instead inside KCP?

**Comment by skywind3000** [comment]
No, tcp's timestamp is 32-bits too. Integer wrapping in both KCP & TCP  is a feature/trick not a flaw, see here:

```cpp
static inline long _itimediff(IUINT32 later, IUINT32 earlier) 
{
	return ((IINT32)(later - earlier));
}
```

**Comment by andersc** [comment]
Ahh.. Great! And thank you for the fast response.
