### ISSUE TITLE
关于ikcp_check的疑问

### ISSUE THREAD

**Issue by vzex** [skywind3000/kcp#3]
伟哥，ikcp_check这个函数返回的间隔时间一定会小于等于kcp->interval，我不太明白这个是怎么减少update次数的，因为我本身如果是按照kcp->interval这个间隔来更新的话，如果依赖ikcp_check返回的时间更新，会更加频繁才对

**Comment by vzex** [comment]
补充一下，看源代码，ikcp_update小于interval的话重复执行是没有效果，所以不知道ikcp_check到底如何使用

**Comment by skywind3000** [comment]
它的作用就是判断，再没有新的数据包输入的情况下，什么时候需要再发送下一个包（窗口探测，或者重发等）。而如果有新的数据包输入了（不管是ACK还是PUSH），或者你调用了 ikcp_send，那么下一个interval就需要调度update，然后再check。你可以创建后 kcp->interval = 1，或者更我一样使用核心interval=10ms的时钟调度器（比如linux内核的那个timer实现版本）。不过如果你不需要管理1000个以上的 kcp对象的话，还是不要用check比较好，这部分代码写起来比较烦。

**Comment by vzex** [comment]
好的，这个函数我还是不用了 -. -!
