### ISSUE TITLE
ToDesk使用KCP建立P2P时,UDP容易丢包

### ISSUE THREAD

**Issue by ji4ozhu** [skywind3000/kcp#304]
ToDesk 目前屏幕传输,文件传输的 P2P部分是基于KCP实现的.
但是目前发现,移动网络,长城宽带 有UDP丢包的情况.
电信没有,联通也没有发现.
有哪个大神有办法防止或者降低UDP丢包的方法吗?

**Comment by skywind3000** [comment]
丢包发生时，kcp 堆积的数据会变多，就是：`ikcp_waitsnd` 的返回值会变大，当超过一定阈值，你需要控制你发送的量。

再，丢包发生时，如果带宽还够用，可以用 fec 降低丢包：

https://github.com/skywind3000/kcp/wiki/KCP-Best-Practice

前向纠错简单点可以 4+1，四个数据包，然后再发一个 p1-p4 亦或后的冗余包，如果这 5 个包内任意丢失一个，
都可以通过其他四个亦或得到。

**Comment by ji4ozhu** [comment]
thanks
