### ISSUE TITLE
应用层如何判读kcp的output数据发送完

### ISSUE THREAD

**Issue by KublaikhanGeek** [skywind3000/kcp#321]
你好：
我有一个应用场景，服务端会启动一个进程用来发送文件，循环读完文件并调用完ikcp_send后，进程退出了，导致缓冲度列里的数据还没有来得及发送。所以想判读缓冲队列里的数据是否发送完，然后退出进程。

**Comment by skywind3000** [comment]
接收方成功接收完文件以后给发送方回一条 ”文件成功接收“ 的消息，发送方收到后再结束就行了。

**Comment by KublaikhanGeek** [comment]
> 接收方成功接收完文件以后给发送方回一条 ”文件成功接收“ 的消息，发送方收到后再结束就行了。

谢谢回答。
