### ISSUE TITLE
关于fec

### ISSUE THREAD

**Issue by metalwood** [skywind3000/kcp#33]
KCP只负责重传，并未加纠错，是不是因为公网传输时fec效果很有限，所以没必要？我们cto说公网里fec作用不大，我不知道是不是这样，请教skywind。谢谢！

**Comment by skywind3000** [comment]
1. 我在公网用了fec效果十分明显。
2. KCP不负责纠错，因为`这是传输层的事情`，你下面肯定要走udp，你那一层肯定就要做纠错了，为何要放在kcp上做，tcp做纠错是因为tcp裸跑在ip上面的，kcp跑在udp上，udp本身有纠错，而且，udp上面还有一层你自己写的传输封装，那层代码肯定也要考虑纠错，那我kcp里面又来占用几个头部字节纠错干嘛呢？

**Comment by metalwood** [comment]
udp本身有了纠错，但是还不够，还要在udp之上继续做更好的纠错，我这样理解对吧。另外，kcp结合fec这块能否提供开源项目或者资料呢？fec的开源代码真的很少。谢谢skywind！

**Comment by skywind3000** [comment]
嗯，最简单的重复fec，或者异或fec，我的wiki里面讲了吧，发送三个包后再发一个异或包（内容等于前三个包每个字节xor），这四个包里任意一个丢失都可以从其他三个xor恢复出来。这套机制很简单，自己写吧，这年头居然没开源就做不了了？

**Comment by icechenbing** [comment]
> 

另外，接受端接收到重传包后，发现可以fec恢复所在分组，就无需等待该分组中另外丢包。

**Comment by skywind3000** [comment]
一层模型做一层模型的事情，不要猫捉耗子啊，wifi 传输也有 fec 啊

**Comment by rorschach-py** [comment]
> > 
> 
> 另外，接受端接收到重传包后，发现可以fec恢复所在分组，就无需等待该分组中另外丢包。

如果你设计5G 6G手机的空口协议，挑战无线信道的物理极限，那确实必要，fec和arq结合，减少协议层级，可以减少层层协议封装带来的开销。

**Comment by skywind3000** [comment]
每个包多了几个字节而已，没意义
