### ISSUE TITLE
请教一个UDP的SO_REUSEPORT问题

### ISSUE THREAD

**Issue by yxhtx** [skywind3000/kcp#333]
我正在使用KCP+UDP实现类似TCP的listen+accpet的功能，具体如下：
服务器启动一个UDP socket绑定一个端口（SO_REUSEADDR+SO_REUSEPORT），接收来自客户端的第一个包，然后创建一个新的UDP socket，同样绑定到这个端口（也使用SO_REUSEADDR+SO_REUSEPORT），再使用connect来指定客户端ip和port，预期客户端的后续包都将被这个新socket接收处理。
目前的问题是：在一些机器上表现符合预期，但是在某些机器上客户端发来的包却被其他socket接收了，请问这是什么原因？

**Comment by skywind3000** [comment]
谁给你这个预期的啊

yxhtx ***@***.***>于2021年11月27日 周六13:19写道：

**Comment by yxhtx** [comment]
在某些服务器运行时确实表现是对的，而且也使用了上百个角色来测试。
您的意思是这在理论上是不行的吗？

**Comment by yxhtx** [comment]
如果有 N 个 udp_sock，来自于多个客户端的 UDP datagram 会被均匀地分配给这些 udp_sock 处理，同一个客户端的数据总是分配给同一个 udp_sock。
如果按照这句描述里说的“均匀分配 ”，这方案应该是不可行的，所以发了这个issue来请教一下。

**Comment by cary-zhou** [comment]
udp socket调用bind和connect绑定本地和对端地址端口后，理论上只要是同一五元组的数据到本地后是被同一个udp socket接收处理的，中间被其他socket接收处理了，可能存在中间NAT设备为了达到负载均衡或多链路叠加的目的把一条udp会话的数据包拆分到了不同链路上传输，那么到达本地后将不能够匹配同一五元组，比如ipt_nth模块就能实现这样的效果。

**Comment by cod1ingcoding** [comment]
客户端还需要connect设定服务器地址、端口。如果设置了，在同一个局域网内应该是没有问题的，不过正如@cary-zhou 所说，如果客户端在nat下，因为udp nat的不确定性，预想可能就会有偏差。
