### ISSUE TITLE
主动丢包怎么实现？大家有什么好的办法么？

### ISSUE THREAD

**Issue by symsimmy** [skywind3000/kcp#353]
如果 server 端有数据积压，但是发到 client 已经没有意义了，需要主动丢弃。想请问下大家，有什么好的方法实现主动丢包么？
场景和下面这个类似：

[#336]

**Comment by skywind3000** [comment]
主动丢弃 snd_buf 里过长的数据即可。

**Comment by symsimmy** [comment]
> 外面分析下，主动丢弃 snd_buf 里过长的数据即可。做细点的话，可以主动丢弃重发次数过高的包。

丢弃重发次数过高的包，可以理解的。过长的数据是指什么呢？

**Comment by skywind3000** [comment]
堆积过多的话，说明你想发的数据速度超过网络能力，得丢弃啊。

**Comment by symsimmy** [comment]
> 堆积过多的话，说明你想发的数据速度超过网络能力，得丢弃啊。

了解了，谢谢
