### ISSUE TITLE
安全丢包机制

### ISSUE THREAD

**Issue by Julyllll** [skywind3000/kcp#357]
您好，有两个问题想请教一下：
1.请问有实现丢包机制吗？
2.请问kcp源码中，当数据包重传了20次之后，将kcp->state设置为-1之后，好像就没有做其他处理了，那么是否会继续重传呢？
```c
 if (segment->xmit >= kcp->dead_link) {
                kcp->state = (IUINT32)-1;
}
```

**Comment by skywind3000** [comment]
当然会，这个只是个标志而已，处理不处理看上层。
