### ISSUE TITLE
做了 Node.js 扩展，希望能放置到【相关应用】中，还有关于版权协议的问题

### ISSUE THREAD

**Issue by leenjewel** [skywind3000/kcp#36]
Hi

感谢你贡献的 kcp 开源项目，我封装了 Node.js 扩展，项目地址在

[https://github.com/leenjewel/node-kcp](https://github.com/leenjewel/node-kcp)

希望能放置在 kcp 项目的 README 的【相关应用】列表中

最后，我看到你对项目使用了 GPL v2 协议，我使用了  Apache v2.0 协议，是有[冲突](http://www.gnu.org/licenses/license-list.html#apache2)的，考虑到 GPL 协议有些过于“强硬” ,是否能考虑更换可以兼容 Apache v2.0 的协议？

祝你愉快~

**Comment by skywind3000** [comment]
已经增加链接，另协议你不用 care

**Comment by leenjewel** [comment]
Thx

**Comment by smilexu** [comment]
我可以用这个项目的C实现与 node-kcp里面的nodejs实现直接通信吗？ @leenjewel

**Comment by leenjewel** [comment]
可以直接来 node-kcp 下面的 issues 讨论，没太明白你的意思，kcp 本身的 C 是不能直接被 nodejs 所用的，node-kcp 做的就是在 kcp 和 nodejs 之间用 C++ 封装了一下，做了“桥梁”，是 nodejs 可以调用 kcp 本身的 C 实现

**Comment by smilexu** [comment]
@leenjewel 谢谢回复，我的意思是拿node-kcp 做server端，kcp C 做client端，或者反过来。按照你说的node-kcp只是kcp C实现的nodejs封装的话，那应该就不会有问题。准备试试，如果有问题的话，我会在node-kcp下面提问 :)

**Comment by leenjewel** [comment]
@smilexu 明白了，虽然我没有做过类似的测试，不过，应该是不会有问题的。你多测测吧，有问题随时沟通 :-)
