### ISSUE TITLE
能不能和raknet比较一下。

### ISSUE THREAD

**Issue by heroboy** [skywind3000/kcp#37]
或者是，如何评价raknet呢？
http://www.jenkinssoftware.com/
https://github.com/OculusVR/RakNet

因为之前做了个商业rts游戏，山寨lol。用的是raknet，一切都很好。
所以能不能以你的专业眼光来比较或评价一下raknet。好让我下一次有选择或者项目重做的话，能选择你的kcp呢。

**Comment by heroboy** [comment]
我看完文档和.h文件有几个疑惑。

1. 整篇文档都没提及kcp是类似tcp流式的协议开始类似udp基于包的。虽然看`ikcp_recv`的接口，感觉是流式的协议。

2. 感觉完全不知道怎么做一个服务器程序，来**接收**客户端。是不是应该每收到一个udp包，根据remote_ip,remote_port来对应一个`ikcpcb`呢？

**Comment by skywind3000** [comment]
1. 同时支持流失和包式：默认是包式，但是你可以创建后两端使用 kcp->stream = 1 设置成流式协议。
2. 客户端发上来的包都要包含一个会话编号  conv，你通过这个 conv 判断属于本地哪个会话，remote ip/port 只是确定了会话以后用来验证来源是否合法用的。

**Comment by skywind3000** [comment]
比较过 libenet  udt 均取得了不错的成绩，你要评测可以使用 kcptun 来评测。kcptun 加速 shadowsocks 上网十分流畅。

**Comment by heroboy** [comment]
```cpp
// user/upper level recv: returns size, returns below zero for EAGAIN
int ikcp_recv(ikcpcb *kcp, char *buffer, int len);
```
如果是包式的，那么如何知道收到的包多大呢，如果传入的buffer比较小的话。
例如：应该收1000个字节的包，传入的buffer只有500个字节。这时候`ikcp_recv`会返回0，告诉我重新收一次，因为buffer太小了。还是返回1000，告诉我这个包有1000个字节，然后我发觉传入的buffer只有500个字节，所以再次以1000字节的buffer收一次才收到这个包吗？

关于第二个问题，是不是服务器只需要一个udp socket一个`ikcpcb`，然后无论从哪里收到的包，都传给`ikcp_input`吗？那有两个问题，
1. 谁分配的conv。应该让服务器来分配的，但是根据`ikcp_create`来看是客户端自己决定的。
2. 当用`ikcp_recv`收包的时候，不知道哪个会话的包啊，没有返回conv啊。

**Comment by heroboy** [comment]
能不能写个伪代码，来描述一下，服务器应该怎么写啊。

**Comment by bitkevin** [comment]
应该在UDP层，自己再实现一套消息格式，用于协商`conv`编号、以及新建、断开、重连之类的基本管理操作。从UDP收到包后，先根据自定义消息格式，处理完UDP包后，再调用`ikcp_xxxx()`进行处理响应的数据。

**Comment by caoli5288** [comment]
@bitkevin 这操作在tcp层，或者直接用http(s)还方便些。

**Comment by heroboy** [comment]
时间太久了，我close了。

**Comment by skywind3000** [comment]
主页下面已经有raknet的比较了，不知道你看到没有？
