### ISSUE TITLE
使用哪种FEC最高效，请指点。

### ISSUE THREAD

**Issue by metalwood** [skywind3000/kcp#38]
目前已知的FEC方案包括：
1、openfec.org
2、tahoe-lafs.org/trac/zfec
3、Reed Solomon

哪种FEC理论上最能优化传输效率、避免重传呢？还是有我不知道的更好方案？还是哪两种结合使用？请您指点。

**Comment by skywind3000** [comment]
reed solomon，kcptun就是用的reed solomon。
