### ISSUE TITLE
这里检测使用的buffer超过mtu就output一次是不是会导致seg分成两段

### ISSUE THREAD

**Issue by newNcy** [skywind3000/kcp#395]
![image](https://github.com/skywind3000/kcp/assets/19602632/02fa4fb7-9f14-46bd-9f62-e0a5ca473808)

如图

**Comment by skywind3000** [comment]
当然要拆分，但是接收的时候会归并的。

**Comment by newNcy** [comment]
哦哦 谢谢韦老师 所以是一个seg分成两个udp报文，然后收到第一个看len不够等下次接收吗
我一开始看到有mtu下意识觉得是将要放入buffer的数据会导致超出mss就发，细看才发现已经超了，不实现成前者是什么原理

**Comment by skywind3000** [comment]
不怎么看啊，你可以再做个类似 kcp 的东西，同时支持多种协议。

**Comment by newNcy** [comment]
好的 我也怕给kcp改坏了🐶

**Comment by newNcy** [comment]
一个seg分在两个udp报文里，后面的一段没有seg头，先到了是不是属于这两个都丢了，或者这后半段当成一个正常包处理

**Comment by newNcy** [comment]
![image](https://github.com/skywind3000/kcp/assets/19602632/3c8d2fd5-70a6-4a8b-97ca-831d14d2419d)

这个头文件里没有
