### ISSUE TITLE
test.cpp 运行结果不符合预期

### ISSUE THREAD

**Issue by RRRaymond** [skywind3000/kcp#397]
我的运行结果如下，可以明显看到默认模式rtt和总耗时明显偏大，重复测了很多次都是这样按照test.cpp中注释，三者总耗时应当差不多，rtt也不会有这么大的差距。
default mode result (29591ms):
avgrtt=5522 maxrtt=9986 tx=333

normal mode result (20265ms):
avgrtt=162 maxrtt=557 tx=1304

fast mode result (20139ms):
avgrtt=138 maxrtt=381 tx=1405

我的环境如下：
宿主机：Windows Server 2022 Datacenter
虚拟机（wsl2）：CentOS 7.6.181 x86_64-redhat-linux
编译器：g++ 8.3.1

**Comment by skywind3000** [comment]
总耗时测量的是带宽，rtt 测量的是 latency，二者不是一个东西。

**Comment by RRRaymond** [comment]
> 总耗时测量的是带宽，rtt 测量的是 latency，二者不是一个东西。

还是没有理解，我这边跑test.cpp的时候，等于我默认模式带宽和延迟都比正常模式/快速模式差很多？这正常吗

**Comment by skywind3000** [comment]
正常啊。
