### ISSUE TITLE
为每个kcp设置独立的allocator

### ISSUE THREAD

**Issue by nanoric** [skywind3000/kcp#404]
我打算为每个kcp设置独立的allocator，这样的修改是否会被合并呢？

使用场景：
考虑每个kcp都跑在自己的专用线程上面的情况，这种情况下可以不必使用malloc而是使用非线程安全的内存池作为allocator。
虽然可以使用thread_local（或者类似的技巧）将ikcp的全局malloc改写为去调用调用者线程自己的allocator，但是如果项目之中存在其他使用kcp的代码，可能会导致不兼容：其他代码可能会跨线程使用kcp。

**Comment by skywind3000** [comment]
不合并了，自己改一下吧。
