### ISSUE TITLE
关于WIKI中UDP连接不上的问题

### ISSUE THREAD

**Issue by RJie** [skywind3000/kcp#44]
在阅读WIKI（Cooperate With Tcp Server）的时候，文中写道，国内网络比较特殊，会存在有些UDP连接不上的情况。请教一下，在那些地区，或者哪些情况下，UDP会连接不上，存在这种问题的网络覆盖范围大吗？

**Comment by skywind3000** [comment]
udp 客户端到服务器可以联通 90%的情况，udp p2p可以联通70%的情况。
其他时候走tcp

**Comment by RJie** [comment]
10%也是一个不小的数目。如果服务器只提供基于UDP的服务，还是不太合适

**Comment by skywind3000** [comment]
标准做法是：默认链接udp，udp能用就用udp，用不了就fall back回tcp去。

**Comment by RJie** [comment]
另外请教一个附加问题，UDP的一个recvfrom比较容易出现性能问题，我认为应该没有tcp+epoll的处理能力强。应该如何增加udp server接收的吞吐量呢？

**Comment by skywind3000** [comment]
你把 udp也放到 epoll 对象里啊。
