### ISSUE TITLE
延迟ACK vs 非延迟ACK

### ISSUE THREAD

**Issue by niuys** [skywind3000/kcp#5]
README里有一段 "TCP为了充分利用带宽，延迟发送ACK（NODELAY都没用）", 有个选项TCP_QUICKACK可以控制，但是需要每次recv之后调用，有代价。这里不知道怎么描述可以更准确，吹毛求疵了，哈

**Comment by skywind3000** [comment]
是个好东西，但太过依赖操作系统具体实现了，没法决定运行环境。Windows 下面通过修改注册表也可以调整 tcp 的工作 interval 和 延迟 ack 效果。但全局的，你也不敢改，改了你玩游戏是快了，下文件慢了咋办呀。

**Comment by niuys** [comment]
是的，所以360可以搞个游戏模式？~~~

**Comment by skywind3000** [comment]
是呀，360可以搞一个，不过这个搞法挺流氓的。
