### ISSUE TITLE
Sending redundant data for lower latency on packet loss

### ISSUE THREAD

**Issue by kkimdev** [skywind3000/kcp#50]
This method is described well here http://gafferongames.com/building-a-game-network-protocol/reliable-ordered-messages/ .

In short, for example,

```
P1 == msg1 + msg2 + msg3
P2 == msg2 + msg3 + msg4
P3 == msg3 + msg4 + msg5
```

Then even if P2 is lost, msg4 can be recovered immediately by P3.  This effectively multiples total data transmission size so it can't be for everything, but for sending small data periodically, it is a really effective method.

**Comment by kkimdev** [comment]
Actually, I noticed forward error correction section in this page https://github.com/skywind3000/kcp/wiki/KCP-Best-Practice . Is this already implemented?

**Comment by skywind3000** [comment]
I suppose each different network layer should do different things, 
For FEC, there are to many algorithms, such as: 

1. `repeat`: as your reference
2. `xor`: p1 = m1, p2 = m2, p3 = m3, p4 = m1 ^ m2 ^ m3, any packet of p1-p4 can be recovered by xor other three together.
3. Reed Solomon: a little more complex but more powerful than `repeat` and `xor`

Which one should I intergrate ? just can't decide easily.
The main idea of protocol layer is you can assemble different layers together to fit your need.

for example KCP is just ARQ layer, and you can implement your own fec layer and connect 
them to kcp like this:

1. setup the KCP output callback function to your FEC input api.
2. when a packet is decoded from your FEC layer, input it to KCP by `ikcp_input()`

In my own projects, I have implemented my own reed solomon fec algorithm and make it cooperative with KCP like these.

also, you can make your own encryption layer.

**Comment by skywind3000** [comment]
for simplicity, you can integrate KCP to your TCP server:
1. client should connect to your tcp port at first
2. after login successful, server will send the udp address:port and conv id to client from tcp
3. client send udp packets to server use the conv id and udp address:port.
4. server verify the conv id and knows it is the same client just login successfully from tcp.

And than, FEC and encryption could be implemented inside this `connection management layer`.

**Comment by kkimdev** [comment]
Thanks.  I really love the modular aspect of KCP.  Though initially I thought effective FEC can't be done independently from the ARQ layer implementation as then FEC layer wouldn't have any knowledge about normal packet vs retransmitted packet vs ACK packet which can potentially used to optimize FEC implementation.  But maybe that's not that important in practice or maybe even not needed.

**Comment by skywind3000** [comment]
It is absolutely not necessary for FEC layer to recognize what the packet is, just encode and send them.

**Comment by kkimdev** [comment]
This is a contrived example, but let's say latency is 5ms and a client is sending a packet every 20ms, with one redundant past packet.

```
0ms : Client sends P2 == m1, m2
5ms : Server receives P2 and sends m2-ack
10ms: Client receives m2-ack
20ms: Client sends P3 == m2, m3
```

At the last step, since client knows m2 is received by server from m2-ack, so P3 doesn't have to include m2, but if FEC layer is independent, it doesn't know that.

**Comment by skywind3000** [comment]
Good point !! I think you are right, redundancy is a cost of decouple.

Maybe you have read this good article about it:
[redundancy vs dependencies which is worse](http://yosefk.com/blog/redundancy-vs-dependencies-which-is-worse.html)

I have been using reed solomon as a seperate fec layer successfully for many years,

Projects using kcp successfully are listed here:
https://github.com/skywind3000/kcp/wiki/Success-Stories
