### ISSUE TITLE
超过慢启动阈值后，拥塞窗口的增加算法

### ISSUE THREAD

**Issue by tallongsun** [skywind3000/kcp#6]
if (kcp->cwnd < kcp->ssthresh) {
				kcp->cwnd++;
				kcp->incr += mss;
			}	else {
				if (kcp->incr < mss) kcp->incr = mss;
				kcp->incr += (mss * mss) / kcp->incr + (mss / 16);
				if ((kcp->cwnd + 1) * mss >= kcp->incr) {
					kcp->cwnd++;
				}
			}
超过慢启动阈值后，拥塞窗口的增加算法是基于什么原理？要达到什么效果呢？能不能详细讲一讲。谢谢

**Comment by skywind3000** [comment]
BUG，已修正
