### ISSUE TITLE
关于 mKCP

### ISSUE THREAD

**Issue by oksbsb** [skywind3000/kcp#69]
https://www.v2ray.com/chapter_03/kcp.html 

里面提到 mKCP 中 “对 KCP 协议的改进” 部分，请问有计划实现这些改进么

**Comment by oksbsb** [comment]
抱歉，刚刚看到 https://github.com/skywind3000/kcp/issues/25 里面提到了这个问题，不过我觉得将多个ACK放到一个包里面还是有意义的。

**Comment by sgf** [comment]
@oksbsb  其实我也有同感，不过 作者觉得自己的做法 更好，坚持认为没有多少提升，我后面也只好附会一下，毕竟项目是作者的,哈哈
