### ISSUE TITLE
发送流控问题以及事件触发问题

### ISSUE THREAD

**Issue by huyuguang** [skywind3000/kcp#75]
1，当接收方处理不过来时，例如作为proxy，无法及时把从kcp收到的数据发出时，停止调用kcp_recv，是不是会导致另一方的kcp_send降低发送速度直至停止发送？（类似tcp停止调用recv从而使得tcpwnd降低抑制发送方的发送速度）

2，发送方的kcp_send似乎是无限制的缓存需要发送的数据。那么是否应该在应用层或者封装层判断ikcp_waitsnd是否大于某个阈值，主动停止发送？

3，应该在何时机调用kcp_recv？是否应该在kcp_input传入一个udp包之后立刻循环调用到返回值小于0为止？

4，如果希望用类似asio或者epoll的方式封装异步或者事件触发接口，那么应该怎么判断可读可写事件？是否都是在底层收到一个udp包并且调用kcp_input之后触发读事件和写事件？因为只有收到了udp包才可能确认发送完成降低waitsnd或者得到新数据。是否还应该更细致一点，例如调用ikcp_waitsnd判断waitsnd小于预定义的某个阈值，或者调用ikcp_peeksize确保有可读的数据 之后再发送事件？

**Comment by skywind3000** [comment]
对方需要检测 waitsnd 来判断发送频率。

kcp recv 可以在 input了以后立马判断。

epoll 模式可以用 ikcp_check 配合时间轮实现。

**Comment by huyuguang** [comment]
“epoll 模式可以用 ikcp_check 配合时间轮实现。” 这句话我不太明白，能否说的更细致一点？ 我说下我的理解，你看看是否有问题。
1，在ikcp_check或者每次定时调用ikcp_update时检查ikcp_waitsnd，如果小于某个阈值，则认为可写。2，在每次调用ikcp_input之后，认为此时可读可写。当然此时未必真的可读可写，也可能返回0，那就类似于是假唤醒，上层代码要能处理这种情况。
我个人认为只要有2就行了，似乎用不着1?

**Comment by skywind3000** [comment]
https://github.com/skywind3000/kcp/wiki/KCP-Best-Practice
wiki 上我写过，最下面。

**Comment by huyuguang** [comment]
"标准顺序是每次调用了 ikcp_update后，使用 ikcp_check决定下次什么时间点再次调用 ikcp_update，而如果中途发生了 ikcp_send, ikcp_input 的话，在下一轮 interval 立马调用 ikcp_update和 ikcp_check。 使用该方法，原来在处理2000个 kcp连接且每 个连接每10ms调用一次update，改为 check机制后，cpu从 60%降低到 15%。"  这里面的“**在下一轮 interval** ”我不太明白。这意思是说，如果调用了ikcp_send或者ikcp_input，则立刻调用一次ikcp_check，然后在给定的时间后调用ikcp_update？

**Comment by huyuguang** [comment]
我想我大概知道你什么意思了。你的意思是，总是有一个10ms(或50ms)的定时器，每10ms遍历所有的kcpcb，如果current还没到该kcpcb上次ikcp_check返回的值，就直接跳过，如果到了就调用。如果中途发生了ikcp_send, ikcp_input的话，那么忽略上次调用ikcp_check返回的值，调用update。

我的想法是，我干脆不搞这个定时器了，我每次update之后立刻调用一次check，并且根据返回值设置一个delaytask再调用update。每次send之后，立刻调用一次update并且紧接一次check。每次input之后，立刻调用recv，然后调用一次update并且紧接一次check。这样做会有什么问题吗？

另一个问题，kcp->updated这个值，我在代码里只看到了设置为1，从来没看到设置为0，这里是否有笔误？
