### ISSUE TITLE
流模式和包模式的问题

### ISSUE THREAD

**Issue by huyuguang** [skywind3000/kcp#76]
kcp->stream如果为1的话，是流模式，但是ikcp_recv依然要求len大于至少一个分片的长度。而不是读多少拷多少。感觉不太可用的样子。

kcp->stream如果为0的话，是包模式，是否ikcp_recv保证返回的一定是对方调用ikcp_send时传入的一个完整包？ 看上去似乎也不保证？

**Comment by skywind3000** [comment]
1. 为啥感觉不太可用呢？这是解决 kcptun之类远端一次性send 1MB的数据过来，被切成若干片，接收端受到前面的又不能反馈给用户，有了这个功能后数据可以即时反馈给用户，看视频流畅多了，你传个大于64k的buffer进来就足够了啊。

2. stream=0的话可以保证收到的是一个 send时传过去的完整的包

**Comment by huyuguang** [comment]
kcp->stream为1的时候，ikcp_recv应该可以传入一个任意大于0的len，例如len=4或者1。这才是合理的stream的表现。目前的实现len必须至少为一个分片长度大小，也就是说，len必须是大于mtu才能确保不会失败。
这个语义和tcp的recv/read语义不一致，这会导致一些代码移植起来有点痛苦，需要额外增加一个buffer，还会额外增加一些拷贝。

**Comment by skywind3000** [comment]
这个是 kcp 的特殊流模式，不是tcp的流模式，我又没说这个流模式是和tcp一样的。

**Comment by huyuguang** [comment]
另外，ikcp_send里已经限制了len最大不能超过255*mtu了，所以也不可能一次性发1M大的数据过来...

**Comment by huyuguang** [comment]
麻烦关注一下前面一个issue。ikcp_update是否必须定期调用？是否可以只在ikcp_input/ikcp_send之后立刻调用，下一次按照ikcp_check返回的时间调用？

**Comment by skywind3000** [comment]
可以的，而且 send以后update完了，强制调用一遍flush
