### ISSUE TITLE
deadlink的问题

### ISSUE THREAD

**Issue by huyuguang** [skywind3000/kcp#79]
源码中有如下片段：
			if (segment->xmit >= kcp->dead_link) {
				kcp->state = (IUINT32)-1;
			}
这代码是否意味着某个分片已经重发过很多次（默认20次），始终没有得到对方的ACK？
有点纳闷为什么这里没有对应一个callback。上层判断到state为-1时应该如何处理？是否应该认为连接已经断开？

**Comment by huyuguang** [comment]
我发现在高速网络下，例如loopback下，只要连接数稍多（单线程epoll收发udp同时每10ms调用一次update，kcp连接数100），很容易就触发这个条件，猜想是因为此时RTO非常小，可能很快就触发了重发逻辑？

**Comment by huyuguang** [comment]
情况说明：我调用update的逻辑是每次调用ikcp_input或者ikcp_send之后立刻调用一次ikcp_update，并且立刻随后调用ikcp_check得到下次调用的时间。除此之外没有定时调用ikcp_update的逻辑。

**Comment by skywind3000** [comment]
你可以不用管这个 deadlink，外层自己维护，或者调大一点，kcptun 就是调大了。

**Comment by huyuguang** [comment]
从默认的20改到50之后情况有所好转，但还是会出现少量的deadlink的情况。
另外，这是不是的确意味着这些包发了20次甚至50次还没有收到对方的ACK确认？这个数很大是否意味着额外带宽极大的增加了？

**Comment by skywind3000** [comment]
xmit可以定期复位，
另，我自己是没有使用 deadlink 的，我外层连接管理层自己统计 ping情况，每隔一分钟发起一次 ping，每发起一次会持续每秒钟ping一次，直到收到ping的响应消息。如果超过一分钟ping不通，证明断了。

**Comment by skywind3000** [comment]
你也可以这么设计。

**Comment by huyuguang** [comment]
“xmit可以定期复位，
另，我自己是没有使用 deadlink 的，我外层连接管理层自己统计 ping情况，每隔一分钟发起一次 ping，每发起一次会持续每秒钟ping一次，直到收到ping的响应消息。如果超过一分钟ping不通，证明断了。”

你说的是定期复位kcp->dead_link? 例如发现dead_link错误多了就设置位50，否则20?
实际上tcp里重发次数都不会有20这么多，我猜想重发个3~5次还没ack可能就断开连接了。这里大量出现重发20次以上还是挺让我吃惊的。

另外，有个情况要汇报一下。
测试环境是centos7，用loopback测试。deadlink用默认值20。
我一开始单线程epoll udp_send/udp_recv/kcp_update，这种用法只要有100个kcp连接就很容易出现deadlink，如果把所有的deadlink关掉，持续一段时间，最后只剩15个kcp连接可以一直保持。

然后我改成用单独线程同步调用sendmmsg，单独线程同步调用recvmmsg，一个epoll逻辑线程处理kcp_update(eventfd)。recvmmsg得到包之后带锁插入队列并且唤醒eventfd，发送也类似。这种方式deadlink基本不出现。我上到了1000个kcp也没有问题。到2000个的时候依然会有大量deadlink出现。

**Comment by skywind3000** [comment]
不用纠结 deadlink了，你可以忽略，自己链接管理层用ping检测吧。

这是丢包严重了，请将你的 udp socket 的 SNDBUF, RCVBUF 设大，另外是，不要所有链接公用一个udp 套接字，一般我是几百个个链接公用一个。

**Comment by huyuguang** [comment]
前面的测试里，我已经把udp socket sndbuf和rcvbuf设置成4M了。
我没指望在一对socket上跑10k kcp以上的链接，但是目前测试结果还是令我感觉有点好奇，我只是想找出原因。

**Comment by skywind3000** [comment]
1. 给你的包编序号，查看实在哪一层丢的，这才是最关键的。
2. 你每秒多少个包？单条链接，每个包多大？或者每秒钟试图发送多少字节出去？
3. 最好实际统计一下发包量，

不要依靠deadlink，这只是代表xmit超过上限而已，并没有一个时间段限制，比如5分钟内重发超过多少，也没有判断链接是否真的断了。只能说明历史xmit超过上限了，运行时间越长，丢包越多xmit越大，但不代表
链接失效了，我文档里面都没提让你们单纯依据deadlink判断链接可用，你要这么纠结下个版本我把
deadlink删除了，你们好自己判断。

这只是一个参考值，你应该靠ping才是最准确的。

我单台物理机12K的kcp链接跑过好几年，跑的好好的，关键是找出你代码哪里导致丢包了。epoll是lt还是et？poll到事件以后只读一次还是 while 循环读到完了？4MB的容量太小了，超过的每秒发包量了么？大规模持续发包丢包重传会不会导致带宽雪崩？

别光靠我给你 debug 啊，我有没你代码。

**Comment by huyuguang** [comment]
1，我测试的流量很大，每包10k，流量800MB/s。发送完一个包才发第二个。发送完指写入ikcp的buffer。如果ikcp_waitsnd超过100则等待小于100再发。
2，udp层当然也有deadlink探测，但是这层和ikcp层的deadlink是不一样的。一个udp socket pair之间会有多个ikcp pair。
3，我把kcp连接的逻辑，包括update按conv hash到多个thread上之后，并且优化udp线程和kcp线程之间的切换之后基本不出现kcp deadlink（deadlink=20）的情况了。感觉之前有这个问题还是因为处理不及时导致的。一个udp socket上可以handle 8k个kcp，总流量可以到800MB/s。cpu 1600%。目前瓶颈应该还是在udp线程和kcp线程之间的切换。
4，代码中的deadlink判断是segment->xmit，不是kcp->xmit，我看kcp->xmit已经被废弃了。

**Comment by skywind3000** [comment]
既然已经定位到是来不及处理导致丢包那就不是kcp的事情了

**Comment by Cruirui** [comment]
> 另外是，不要所有链接公用一个udp 套接字，一般我是几百个个链接公用一个。

请问一下，这样做可以带来哪些好处，我在网上似乎没找到相关的内容。 @skywind3000

**Comment by huyuguang** [comment]
@Cruirui 其实无所谓。所有链接公用一个udp端口最大的问题是，如果你的OS不支持SO_REUSEPORT，那么就无法利用多核收发包。

**Comment by medusar** [comment]
mark

**Comment by jaycelq** [comment]
mark

**Comment by wingpuiLaw** [comment]
ping的话有个问题呢，因为现在很多主机都禁止ping了的 @skywind3000 。那还有没有其他方法呢？

**Comment by jaycelq** [comment]
> ping的话有个问题呢，因为现在很多主机都禁止ping了的 @skywind3000 。那还有没有其他方法呢？

@wingpuiLaw 各个业务自己用kcp实现的ping请求，不是icmp的ping

**Comment by wingpuiLaw** [comment]
> @wingpuiLaw 各个业务自己用kcp实现的ping请求，不是icmp的ping
哦哦, 你的意思是还是原来的底层协议? 还是说直接调kcp发送心跳?

**Comment by sgf** [comment]
deadlink 这么快就已经到20了 难道不是rto的设置和更新不及时的问题么？
就算是timer是10ms 一次，rto每发一次就增加50%。那么20次的话rto应该已经增加到一个很高的地步了吧。
可能超过10秒了吧？10秒重发都没有确认的话 判定为连接断开有问题？

**Comment by skywind3000** [comment]
不要参考 deadlink，自己外层设计心跳判断是否活着。
