### ISSUE TITLE
kcp 可以在手机端使用吗？

### ISSUE THREAD

**Issue by gyf19** [skywind3000/kcp#8]
kcp 可以在手机端使用吗？ 不知道大神有没有在uniy3d 项目集成过kcp?   如果可以的话， 最好可以来一个例子，谢谢

**Comment by skywind3000** [comment]
可以，见我文档中最新的评测数据。

**Comment by skywind3000** [comment]
在3G/4G/Wifi下表现良好。

**Comment by gyf19** [comment]
有没有集成kcp的unity3d开源项目？

**Comment by skywind3000** [comment]
这个不得而知，但是kcp在pc和移动上好几个产品都跑得好好的。

**Comment by gyf19** [comment]
赞
