### ISSUE TITLE
Is there anyone who has experience of live streaming optimization by using KCP?

### ISSUE THREAD

**Issue by gnolizuh** [skywind3000/kcp#80]
We, KINGSOFT Cloud inc., are investigating whether there is a way to improve the user's live-stream play experience, and reducing latency over RTMP protocol over tcp what we are using. We have our own Streamer and Player SDK, so it's possible to embed KCP on it. Please comments this issue to help us. Thanks a lot!!

**Comment by gnolizuh** [comment]
Eh, thanks for you to contribute this awesome project..

**Comment by skywind3000** [comment]
请观看，使用 KCP的产品不完全列表：
https://github.com/skywind3000/kcp/wiki/HISTORY

据我所知，使用 KCP加速视频直播的产品/CDN，不下5家。

**Comment by gnolizuh** [comment]
CDN分发的话，大部分都是RTMP/HTTP FLV协议，这种方案是用kcptun吗。

我们正在调研用KCP来优化主播上行推流网络，用RTP over KCP可行吗，或者有没有更好的建议。

**Comment by skywind3000** [comment]
下行继续 HTTP/RTMP，上行 UDP + KCP，做好流量控制，做好丢帧，避免顺时拥塞，中间别插啥 RTP了。

**Comment by skywind3000** [comment]
之前bobo很多主播都是学生，住在出租屋里，和人合租，隔壁看个视频，下个东西，她们就卡的不行，上了UDP+KCP以后，即便隔壁开着BT，看着高清，主播也不卡了。

**Comment by gnolizuh** [comment]
哦，了解，KCP本身是可以保证接收数据的顺序，可以不需要jitter buffer来控制了。但直播还需要PTS来做同步，是不是还是得加一些媒体数据头。

**Comment by skywind3000** [comment]
你把 KCP当 TCP用就行啦，以前推流不都是 RTMP over TCP的么，你的那些 PTS，是里面发的内容，不关 KCP的事情。

**Comment by gnolizuh** [comment]
我懂你的意思了，完全把TCP替换成KCP就好了，其他的原封不动，我们尝试的做做看。

不过还是觉得如果有RTMP/RTP over KCP类似的库，用KCP来优live streaming的门槛会大大降低啊。

**Comment by skywind3000** [comment]
有，但是不是我一个人做的，还有很多公司其他人的代码，没法开源。

**Comment by gnolizuh** [comment]
了解，谢谢你的解答，Issue我就关闭了。

**Comment by skywind3000** [comment]
你们可以先用 kcptun 测试一下对推流的优化效果：
1. 主播端直接 RTMP 出去 （模拟丢包）
2. 主播端链接本地 kcptun 端口-> kcp+udp （模拟丢包）->中转服务器->服务器 RTMP 服务器

十分明显的效果。

然后你们可以尝试开发 C版本的 DLL，用来直接加速，不需要多次 tcp/udp转换。
全国部署几个加速点，加速主播上行，把主播上行的 KCP+UDP数据，转成 RTMP数据推给 CDN
光这个事情，流畅率起码提升20%，（一分钟内不卡的用户比例）。

再做一件事情，FEC，我wiki里面有，流畅率再提升10%。

**Comment by gnolizuh** [comment]
好，谢谢你，有结论我再来回复。

**Comment by gnolizuh** [comment]
我用kcptun的几种模式分别和tcp对比了一下，效果确实很好，normal模式下loss 10%性能最好。

**Comment by skywind3000** [comment]
当然，你们用C++封装kcp和fe

**Comment by skywind3000** [comment]
当然，你们c++封装kcp和fec去掉中间代理层主播直接发送kcp数据到自建推流服务器转成rtmp再到附近的cdn，控制好缓冲做好丢帧，调好参数，效果更好。

**Comment by gnolizuh** [comment]
至于怎么融合到nginx流媒体服务器，我们还在调研。by the way, KCP有和QUIC协议对比过性能吗?

**Comment by skywind3000** [comment]
有人对比过基于 quic 的隧道和 kcptun 的隧道性能，kcptun 表现更好，毕竟 quic 主要是服务 http + udp 快速握手多路传文本图片那些的。nginx rtmp ？有项目是推流服务端上面启动一个服务，是客户端直接 KCP 协议上来，该服务翻译一次成 tcp rtmp 协议推给本机 127.0.0.1 的 nginx rtmp 模块。

**Comment by gnolizuh** [comment]
对 nginx-rtmp-module
