### ISSUE TITLE
ts字段为何没有加上接收者在本地等待的时间？

### ISSUE THREAD

**Issue by huyuguang** [skywind3000/kcp#81]
发送者在数据包ts字段保存这个包的发送时间，接收者在ikcp_ack_push函数里把接收到的数据包的ts保存在了acklist，然后在ikcp_flush里把ts放在ack包里发出去。然后发送者收到这个ack包，并且在ikcp_update_ack里用当前时间减去ts得到rto。

问题在于，接收者是周期性的调用ikcp_flush的，它并不是收到包之后就立刻回应ack的，那么这中间的时间也被算在rto里了。

为什么不让接收者在收到数据包之后，记录下本地时间recv_ts，然后在回应ack时，seg->ts += current-recv_ts?

**Comment by skywind3000** [comment]
你读两个tcp实现就知道不用这么纠结了

**Comment by huyuguang** [comment]
tcp估计rto更不准。但是quic很不一样，一方面重发包的sn不一样，另外计算时排除了在端上的等待时间。

**Comment by huyuguang** [comment]
不好意思，我再仔细看了一下代码逻辑，发现目前的设计中这个时间就应该是包含等待时间。
