### ISSUE TITLE
新的RUST库

### ISSUE THREAD

**Issue by Matrix-Zhang** [skywind3000/kcp#82]
kcp: https://github.com/Matrix-Zhang/kcp
纯kcp算法翻译

tokio_kcp: https://github.com/Matrix-Zhang/tokio_kcp
tokio的集成

**Comment by skywind3000** [comment]
好的，您这第一个项目的名称（不是rust的包名），能不能改做 kcp-rust 之类？我和其他推荐放在一起，大家都叫 kcp-xxx，便于区分啊，不然项目名就和这个kcp的c库搞混了，单独看没啥，放一起有点晕。

**Comment by Matrix-Zhang** [comment]
没法弄，因为kcp_rs被抢注了

**Comment by skywind3000** [comment]
kcp-rust ??

**Comment by Matrix-Zhang** [comment]
额。我已经publish了，你干脆就把第二个弄到你的readme算了。。。

**Comment by skywind3000** [comment]
已加入。
