### ISSUE TITLE
ikcp_flush 崩溃

### ISSUE THREAD

**Issue by graysparrow** [skywind3000/kcp#87]
请问下，我的程序在ikcp_update调用ikcp_flush时崩溃在了第1068行，memcpy(ptr, segment->data, segment->len)这一句话上，像是访问了非法内存，请问知道怎么回事吗？？？

**Comment by skywind3000** [comment]
不要放在不同线程里跑，同一个kcp对象。

**Comment by graysparrow** [comment]
就是说创建 kcp对象的线程跟调用kcp_update等各种函数的线程一定要放在同一个线程里对吧？

**Comment by skywind3000** [comment]
是啊，或者你自己加锁。

**Comment by graysparrow** [comment]
就是说只要保证所有kcp函数的调用得是线性序列就行，不能并行执行，就可以吧？

**Comment by skywind3000** [comment]
不是调用顺序，是线程安全，你搜搜其它issue，有讨论
