### ISSUE TITLE
求助：接收端后启动（或者重启）， 发送端发包的 sn 持续增加，超过接收端的 recv_wnd， 导致无法收流。

### ISSUE THREAD

**Issue by shen1985** [skywind3000/kcp#88]
udp + kcp 实现发送端和接收端。
如果接收端启动较慢，或者有重启。 发现包里面的 sn，超过接收端的 recv_wnd（默认32）， 导致无法解析出数据。 
大家遇到过这类问题么，咋解决呀？谢谢啦

**Comment by skywind3000** [comment]
1. 连接慢不会有问题，接收端不发ack，发送端会持续发前面的包。
2. 断线重连请两边重新建立新的 kcp对象。

**Comment by wavebit** [comment]
对于第二点，断线重连为什么要重新建立新的kcp对象，那么缓存里没有发出的包怎么办？
我想的是保持现有的kcp对象，当客户端重连上来时（session id不变，但是客户端的ip地址可能改变了），然后只需要重定向服务端kcp的目的端口到新的端口就可以了. 这样有什么问题吗？

**Comment by skywind3000** [comment]
我靠，就是 linux 你tcp断线重连了也是一个全新的链接好不好？内部都是新建全新的 tcp 对象

**Comment by wavebit** [comment]
还是不理解
kcp实现不是和UDP/TCP无关嘛

**Comment by wavebit** [comment]
还有就是发现断线时，要冻结时间，不update等，保持状态不变。
这样还有问题吗？

**Comment by skywind3000** [comment]
我给你举 tcp 的例子，断线重连，是逻辑层的事情，对于网络层，都是看成全新的链接来处理的，所以不管 kcp 还是 tcp，并没有所谓断线重连的概念，断了就是断了，再连，两边都要创建全新的链接对象，当新连接处理。断线重连是逻辑层的事情。

**Comment by wavebit** [comment]
首先我说的断线重连情况是切换网络，两端状态都在，kcp参数都不变。
重新建立kcp对象，kcp里缓存里所有命令消息是不能直接丢弃。
要么在逻辑层缓存起来，要么从旧kcp中拷贝到新的kcp中。我想了想，如果逻辑层缓存的话，那么就要从kcp返回确认消息，确认哪些命令消息被收到了(不知道用kcp的哪个回调api?)，那么就是再实现一套类似kcp的可靠消息队列。

**Comment by skywind3000** [comment]
你 tcp 切换网络不也断了？tcp你怎么处理，kcp就怎么处理啊

**Comment by wavebit** [comment]
我用的udp，不是tcp...
