### ISSUE TITLE
描述有一丝歧义

### ISSUE THREAD

**Issue by metalwood** [skywind3000/kcp#9]
> 如果永远不丢包那么 KCP和 TCP性能差不多，但网络会卡，造成卡的原因就是丢包和抖动。

这句话有歧义，对KCP不了解的人从字面看上去，“网络会卡”可能是KCP造成的。是不是可以表述成“ 如果网络永远不丢包不抖动，那么 KCP和 TCP性能差不多。”

**Comment by skywind3000** [comment]
多谢提醒，已经修正
