### ISSUE TITLE
question about reliability 传输可靠性的疑问

### ISSUE THREAD

**Issue by cryptogun** [skywind3000/kcp#92]
估计kcptun (ShadowSocks)直接套用了kcp, 我就在这里问了.
这疑问到处都搜了, 没人解释也没人提问.
问题: UDP传输不可靠, kcp可靠的原因是不是加了ACK/UNA重传? 那SS+kcptun可以放心传输大文件了吧?
也就是变种的(改改)UDP, 使得他可以跟TCP对等起来?
强迫症表示必须要问个清楚, 否则不敢用google photos... YouTube看视频倒可以忍.

**Comment by skywind3000** [comment]
当然是靠重传保证可靠

**Comment by caoli5288** [comment]
韦先生脾气真好，，连README都没看就提issue真是无奈

**Comment by cryptogun** [comment]
嗯, 谢谢! 如果我污染了版面, 我道歉.
P.S. kcp和kcptun的readme和issue都看/搜了, 谷歌也搜了. 没有找到相关解释. 否则我标题干嘛还要带上英文. 或许对于你们专业人士来说一句话描述里的`Reliable ARQ Protocol`就足以解释了吧.
可能之前对可靠的理解有偏差吧. 有重传=可靠.
`必须要问个清楚`语气可能有歧义, 非命令语气. 我是说不问浑身难受, 问了现在会被骂. 不过作者编码时我还没出生呢, 相信作者不会计较的:)
P.S. 看来chrome下载pythonanywhere.com的10M文件时, 永不结束, 是他网站的bug.
