### ISSUE TITLE
关于发送端开始发送后，若接收端重启后会无法接收数据

### ISSUE THREAD

**Issue by chundonglinlin** [skywind3000/kcp#94]
经定位发现，如果发送端保持kcp不变，接收端可以接收数据，但是无法把数据放进缓存：
sn > 0, kcp->rcv_nxt = 0
此时该如何处理？ @skywind3000

**Comment by skywind3000** [comment]
看不懂你说的什么。

**Comment by chundonglinlin** [comment]
老大，咋看不懂呢？@skywind3000
接收端重启后，ikcp_input无法把收到的数据放进去。

**Comment by chundonglinlin** [comment]
发现sn>0,kcp->rcv_nxt=0,if判断无法进入。
```
if (_itimediff(sn, kcp->rcv_nxt + kcp->rcv_wnd) < 0) {
	ikcp_ack_push(kcp, sn, ts);
	if (_itimediff(sn, kcp->rcv_nxt) >= 0) {
		seg = ikcp_segment_new(kcp, len);
		seg->conv = conv;
		seg->cmd = cmd;
		seg->frg = frg;
		seg->wnd = wnd;
		seg->ts = ts;
		seg->sn = sn;
		seg->una = una;
		seg->len = len;

		if (len > 0) {
			memcpy(seg->data, data, len);
		}

		ikcp_parse_data(kcp, seg);
	}
}
```

**Comment by skywind3000** [comment]
废话，莫非你还想接收端用新的kcp对象去配对发送端老的kcp？

两边状态要一致，任何一办重启了，两边都要重新创建新的 kcp对象，就是tcp断了在连，内部状态对象也是两边重新建立的。

**Comment by skywind3000** [comment]
就算你用 tcp，客户端重启以后再连过去，服务端难道不是 accept 出一个全新的 socket 和客户端交流，并且老的 tcp socket会被断开。

想想为啥

**Comment by chundonglinlin** [comment]
两边状态要一致意思是两边的kcp参数以及起始值等必须一致相等，不能一边已经开始计数，另一端又重新从0计数！此时比较合理做法，client端检测到连接断开后应重新创建新的kcp。

**Comment by chundonglinlin** [comment]
但是若使用udp传输，一般无法判断连接状态，是否使用辅助机制来确认是否需要重新创建kcp？@skywind3000

**Comment by skywind3000** [comment]
你这是要我重头教你一遍的节奏啊？看看 kcptun 的代码吧。

**Comment by chundonglinlin** [comment]
老大就是v5
