### ISSUE TITLE
请教：如果一个包进行了分片，kcp怎么保证收到了该包的所有分片后才把该包从rcv_buf移入rcv_queue队列？

### ISSUE THREAD

**Issue by liuchengguang** [skywind3000/kcp#96]
Hi，有几个疑问请教一下：
问题1）：发送端调用ikcp_send()发送数据时，如果该包产生了分片, 假设分为2, 1,0 三个segment,  接收端在收到底层网络数据时触发调用ikcp_input  --> ikcp_parse_data ，在函数ikcp_parse_data  在判断是否把rcv_buf中缓存的segment移入到rcv_queue时，仅判断了 if (seg->sn == kcp->rcv_nxt && kcp->nrcv_que < kcp->rcv_wnd)， 类似的判断ikcp_recv也存在， 那是否存在如下可能性： 3个分片中编号0，1的分片已经收到，并且已移入rcv_queue队列， 但编号2的segment 没有及时到， 而其他包的分片先到了，是否存在其他包的分片先被移入rcv_queue ?
若存在这种可能性，则上层调用ikcp_recv从rcv_queue获得数据包的逻辑就是有问题的，比如：ikcp_recv函数合并分片的处理逻辑中只是根据segment的frg(分片编号)来判断是否一个包的结束，类似的ikcp_peeksize处理逻辑也是如此。

问题2）：在收到底层网络数据时调用ikcp_input(ikcpcb *kcp, const char *data, long size)进行处理，如果接收的数据大小size 超过整数个数据分片segment时， 从whie(1)循环处理逻辑看 存在丢弃多余数据（非整片）的可能性的，这是否有问题？

**Comment by skywind3000** [comment]
代码你看漏了，可以保证，没有问题。

**Comment by liuchengguang** [comment]
具体的逻辑在哪块能指点一下吗？ 
第二个问题，麻烦也解惑一下
多谢多谢！！

**Comment by skywind3000** [comment]
rcvbuf里的包是不连续的，可能会有3，6，7，9这样，但是rcv里的都是连续的，成功接受了的

**Comment by liuchengguang** [comment]
问题1 我大概明白了， seg->sn == kcp->rcv_nxt 的判断是可以保证rcv_queue里的是连续的， 但是 有个问题： 上层调用ikcp_recv()来获取数据，获得的数据并不能保证是一个完整的包(也就是可能只是获得了该包的部分segment),  就这样把非完整丢给上层去处理吗？

**Comment by skywind3000** [comment]
你自己没读懂

**Comment by liuchengguang** [comment]
我重新读了一遍， 搞明白了怎么保证是整包提供给上层的。
但 ikcp_input(ikcpcb *kcp, const char *data, long size) 这个函数处理的data 如果其大小是个非整片的包，那么非整片的数据是否没有处理？
